In [ ]:
%reload_ext autoreload
%autoreload 2

In [ ]:
import numpy as np
from functools import partial

import xclib.data.data_utils as du, scipy.sparse as sp

from sugar.statistics import *
from sugar.core import *
from xcai.data import *

# `LF-WikiSeeAlsoTitles-320K`

In [ ]:
data_dir = '/home/scai/phd/aiz218323/scratch/datasets/benchmarks/(mapped)LF-WikiSeeAlsoTitles-320K/'
save_dir = '/home/scai/phd/aiz218323/scratch/datasets/wikipedia/20250123/LF-WikiSeeAlsoTitles-320K/'
new_dir = '/home/scai/phd/aiz218323/scratch/datasets/benchmarks/20250123-LF-WikiSeeAlsoTitles-320K/'
metadata_type = 'category'

np.random.seed(10)
indices = np.random.permutation(693082)[:10]

updated_show_func = partial(show_updated_dataset, save_dir, metadata_type, idxs=indices)

show_func = partial(show_dataset, metadata_type=metadata_type, idxs=indices)

## Versions

### `old-old-old`

In [ ]:
o = show_func(data_dir, encoding='latin-1')

/home/scai/phd/aiz218323/.local/lib/python3.9/site-packages/xclib-0.97-py3.9-linux-x86_64.egg/xclib/data/data_utils.py:263: UserWarning: Header mis-match from inferred shape!
  warnings.warn("Header mis-match from inferred shape!")

                               # Entries  # Features  \
Split Dataset
Train Main                        693082      312330
      Query Category Metadata     693082      656086
      Label Category Metadata     312330      656086
Test  Main                        177515      312330
      Query Category Metadata     177515      656086
      Label Category Metadata     312330      656086

                               Avg. Entries per feature  \
Split Dataset
Train Main                                         4.67
      Query Category Metadata                      5.17
      Label Category Metadata                      1.72
Test  Main                                         1.73
      Query Category Metadata                      1.27
      Label Category Metadata                      1.72

                               Avg. Feature per entry  \
Split Dataset
Train Main                                       2.11
      Query Category Metadata                    4.89
      Label Category Metadata                    3.61
Test  Main                                       3.05
      Query Category Metadata                    4.68
      Label Category Metadata                    3.61

                               Max. Entries per feature  \
Split Dataset
Train Main                                         2929
      Query Category Metadata                     43980
      Label Category Metadata                      3001
Test  Main                                          309
      Query Category Metadata                      7746
      Label Category Metadata                      3001

                               Max. Feature per entry  \
Split Dataset
Train Main                                         57
      Query Category Metadata                     280
      Label Category Metadata                     270
Test  Main                                        129
      Query Category Metadata                     242
      Label Category Metadata                     270

                               # Features without entry  \
Split Dataset
Train Main                                            0
      Query Category Metadata                     48622
      Label Category Metadata                    329013
Test  Main                                            0
      Query Category Metadata                    367347
      Label Category Metadata                    329013

                               # Entries without feature
Split Dataset
Train Main                                             0
      Query Category Metadata                       9899
      Label Category Metadata                      72609
Test  Main                                             0
      Query Category Metadata                       3961
      Label Category Metadata                      72609

data_input_text : Certificate of Formula Compliance
lbl2data_input_text : ['Certificate of Origin']
cat2data_input_text : ['International trade documents', 'Cosmetic industry']
cat2lbl2data_input_text : [[]]

data_input_text : 2017 Sunwolves season
lbl2data_input_text : ['Sunwolves', '2017 Super Rugby season']
cat2data_input_text : ['Sunwolves seasons', '2016â\x80\x9317 in Japanese rugby union', '2017 Super Rugby season by team', '2017â\x80\x9318 in Japanese rugby union']
cat2lbl2data_input_text : [['2015 establishments in Japan', 'Super Rugby teams', 'Sunwolves', 'Rugby clubs established in 2015', 'Sports teams in Tokyo', 'Rugby union in Singapore'], ['Super Rugby seasons', '2016â\x80\x9317 in Japanese rugby union', '2017 in South African rugby union', '2017 rugby union tournaments for clubs', '2017 in Argentine rugby union', '2017â\x80\x9318 in Japanese rugby union', '2017 Super Rugby season', '2017 in Australian rugby union', '2017 in New Zealand rugby union']]

data_input_text : Hadza people
lbl2data_input_text : ['Twa peoples', 'Aka people', 'Bushmen']
cat2data_input_text : ['Ethnic groups in Tanzania', 'Indigenous peoples of East Africa', 'Hunter-gatherers of Africa']
cat2lbl2data_input_text : [[], ['Modern nomads', 'African Pygmies', 'Ethnic groups in the Central African Republic', 'Ethnic groups in the Democratic Republic of the Congo'], []]

data_input_text : The Lost City (2005 film)
lbl2data_input_text : ['List of American films of 2005']
cat2data_input_text : ['American films', '2000s drama films', 'Lions Gate Entertainment films', '2005 films', 'Films set in Cuba', 'Mafia films', 'American political drama films', 'Films set in Havana', 'Cultural depictions of Che Guevara', 'Films shot in the Dominican Republic', 'Cultural depictions of Meyer Lansky']
cat2lbl2data_input_text : [['2005 in American cinema', 'Lists of American films by year', 'Lists of 2005 films by country or language']]

data_input_text : Testability
lbl2data_input_text : ['Scientific method', 'Contingency', 'Testability', 'Observability', 'Controllability']
cat2data_input_text : ['Philosophy of science', 'Logic']
cat2lbl2data_input_text : [['Philosophy of science', 'Scientific revolution', 'Scientific method'], [], ['Philosophy of science', 'Logic'], ['Classical control theory'], ['Classical control theory']]

data_input_text : Veterans Memorial Parkway (Evansville)
lbl2data_input_text : ['U.S. Roads', 'Indiana']
cat2data_input_text : ['Parkways in the United States', 'Transportation in Evansville, Indiana', 'Roads in Indiana', 'Transportation in Vanderburgh County, Indiana']
cat2lbl2data_input_text : [[], ['Articles containing video clips', 'States of the United States', 'U.S. states with multiple time zones', 'States and territories established in 1816', 'Midwestern United States', 'Indiana', '1816 establishments in the United States']]

data_input_text : Manchester Boddy
lbl2data_input_text : ['Charles E. Downs', 'C.H. Garrigues']
cat2data_input_text : ['1967 deaths', 'Businesspeople from Los Angeles', '1891 births', 'California Democrats', 'American anti-communists', 'California Republicans', 'American newspaper publishers (people)', 'People from La CaÃ±ada Flintridge, California']
cat2lbl2data_input_text : [['20th-century American politicians', '1898 births', '1967 deaths', 'California Republicans', 'Los Angeles City Council members'], []]

data_input_text : Lafayette B. Mendel House
lbl2data_input_text : ['National Register of Historic Places listings in New Haven, Connecticut', 'List of National Historic Landmarks in Connecticut']
cat2data_input_text : ['National Historic Landmarks in Connecticut', 'Houses on the National Register of Historic Places in Connecticut', 'National Register of Historic Places in New Haven, Connecticut', 'Houses completed in 1858', 'Houses in New Haven, Connecticut']
cat2lbl2data_input_text : [['History of New Haven, Connecticut', 'National Register of Historic Places in New Haven, Connecticut', 'Lists of National Register of Historic Places in Connecticut by city'], ['Connecticut-related lists', 'National Historic Landmarks in Connecticut', 'Lists of National Historic Landmarks by state']]

data_input_text : Ferriday Commercial Historic District
lbl2data_input_text : ['National Register of Historic Places listings in Concordia Parish, Louisiana']
cat2data_input_text : ['Historic districts on the National Register of Historic Places in Louisiana', 'Italianate architecture in Louisiana', 'Concordia Parish, Louisiana']
cat2lbl2data_input_text : [['National Register of Historic Places in Concordia Parish, Louisiana', 'Lists of National Register of Historic Places in Louisiana by parish']]

data_input_text : 1408 (film)
lbl2data_input_text : ['List of ghost films', 'Cell', 'List of adaptations of works by Stephen King']
cat2data_input_text : ['American films', 'Films shot at Pinewood Studios', 'American supernatural horror films', 'American horror thriller films', 'American psychological horror films', 'Films directed by Mikael HÃ¥fstrÃ¶m', '2007 horror films', '2000s horror thriller films', 'Films about writers', 'Films set in hotels', 'Films set in Manhattan', 'Films shot in London', 'Films shot in Los Angeles', 'Films shot in New York City', 'Films based on works by Stephen King', 'Films based on short fiction', 'Films shot at Elstree Studios', '2007 films', 'Films scored by Gabriel Yared', 'Screenplays by Scott Alexander and Larry Karaszewski', 'Films produced by Lorenzo di Bonaventura']
cat2lbl2data_input_text : [['Ghost films', 'Ghosts in television', 'Suspense', 'Thrillers', 'Fictional ghosts', 'Lists of horror films', 'Lists of films by topic', 'Lists of films by common content'], [], ['Lists of films based on works', 'Lists of television series based on works', 'Adaptations of works by Stephen King']]

### `old-old-new`

In [ ]:
o = updated_show_func(x_prefix='old', y_prefix='old', z_prefix='new')

                               # Entries  # Features  \
Split Dataset
Train Main                        693082      312330
      Query Category Metadata     693082      810093
      Label Category Metadata     312330      810093
Test  Main                        177515      312330
      Query Category Metadata     177515      810093
      Label Category Metadata     312330      810093

                               Avg. Entries per feature  \
Split Dataset
Train Main                                         4.67
      Query Category Metadata                      4.48
      Label Category Metadata                      1.87
Test  Main                                         1.73
      Query Category Metadata                      1.10
      Label Category Metadata                      1.87

                               Avg. Feature per entry  \
Split Dataset
Train Main                                       2.11
      Query Category Metadata                    5.24
      Label Category Metadata                    4.85
Test  Main                                       3.05
      Query Category Metadata                    5.03
      Label Category Metadata                    4.85

                               Max. Entries per feature  \
Split Dataset
Train Main                                         2929
      Query Category Metadata                     36700
      Label Category Metadata                      3836
Test  Main                                          309
      Query Category Metadata                      6639
      Label Category Metadata                      3836

                               Max. Feature per entry  \
Split Dataset
Train Main                                         57
      Query Category Metadata                     245
      Label Category Metadata                     247
Test  Main                                        129
      Query Category Metadata                     247
      Label Category Metadata                     247

                               # Features without entry  \
Split Dataset
Train Main                                            0
      Query Category Metadata                     73210
      Label Category Metadata                    388883
Test  Main                                            0
      Query Category Metadata                    472596
      Label Category Metadata                    388883

                               # Entries without feature
Split Dataset
Train Main                                             0
      Query Category Metadata                      60302
      Label Category Metadata                      25693
Test  Main                                             0
      Query Category Metadata                      13172
      Label Category Metadata                      25693

data_input_text : Certificate of Formula Compliance
lbl2data_input_text : ['Certificate of origin']
cat2data_input_text : ['Cosmetic industry', 'International trade documents']
cat2lbl2data_input_text : [['Export', 'International trade documents']]

data_input_text : 2017 Sunwolves season
lbl2data_input_text : ['Sunwolves', '2017 Super Rugby season']
cat2data_input_text : ['2016–17 in Japanese rugby union', 'Sunwolves seasons', '2017–18 in Japanese rugby union', '2017 Super Rugby season by team']
cat2lbl2data_input_text : [['2020 disestablishments in Japan', 'Sunwolves', 'Rugby clubs established in 2015', '2015 establishments in Japan', 'Rugby union in Singapore', 'Rugby union clubs disestablished in 2020', 'Super Rugby teams', 'Rugby union teams in Tokyo'], ['2017 in Argentine rugby union', '2016–17 in Japanese rugby union', '2017 in Australian rugby union', '2017 rugby union tournaments for clubs', 'Super Rugby seasons', '2017 Super Rugby season', '2017 in New Zealand rugby union', '2017 in South African rugby union', '2017–18 in Japanese rugby union']]

data_input_text : Hadza people
lbl2data_input_text : ['Twa', 'Aka people', 'San people']
cat2data_input_text : ['Hunter-gatherers of Africa', 'Indigenous peoples of East Africa', 'Ethnic groups in Tanzania']
cat2lbl2data_input_text : [['Ethnic groups in Zambia', 'Ethnic groups in Botswana', 'Ethnic groups in the Democratic Republic of the Congo', 'African Pygmies', 'Ethnic groups in Namibia', 'Ethnic groups in Angola'], ['Modern nomads', 'African Pygmies', 'Ethnic groups in the Democratic Republic of the Congo', 'Ethnic groups in the Central African Republic'], ['Hunter-gatherers of Africa', 'African nomads', 'Ethnic groups in Zimbabwe', 'Ethnic groups in Botswana', 'Coloureds', 'Indigenous peoples of Southern Africa', 'San people', 'Ethnic groups in Namibia', 'Ethnic groups in Angola']]

data_input_text : The Lost City (2005 film)
lbl2data_input_text : ['List of American films of 2005']
cat2data_input_text : ['Films about Jewish-American organized crime', 'Cultural depictions of Meyer Lansky', '2005 drama films', '2000s political drama films', 'Films set in Havana', 'Magnolia Pictures films', 'American political drama films', 'Films about the American Mafia', '2000s American films', 'Lionsgate films', 'Films shot in the Dominican Republic', '2005 films', 'Films set in 1958', 'Cultural depictions of Che Guevara']
cat2lbl2data_input_text : [['Lists of American films by year', '2005 in American cinema', 'Lists of 2005 films by country']]

data_input_text : Testability
lbl2data_input_text : ['Scientific method', 'Contingency', 'Testability', 'Observability', 'Controllability']
cat2data_input_text : ['Empiricism', 'Logic', 'Observation', 'Scientific method', 'Philosophy of science']
cat2lbl2data_input_text : [['Scientific method', 'Empiricism', 'Philosophy of science', 'Scientific Revolution'], [], ['Empiricism', 'Logic', 'Observation', 'Scientific method', 'Philosophy of science'], ['Classical control theory'], ['Classical control theory']]

data_input_text : Veterans Memorial Parkway (Evansville)
lbl2data_input_text : ['Numbered highways in the United States', 'Indiana']
cat2data_input_text : []
cat2lbl2data_input_text : [['Road signs in the United States', 'United States state insignia', 'State highways in the United States', 'Highways in the United States'], ['States and territories established in 1816', 'States of the United States', 'Midwestern United States', 'Indiana', 'Articles containing video clips', '1816 establishments in the United States', 'Contiguous United States']]

data_input_text : Manchester Boddy
lbl2data_input_text : ['Charles E. Downs', 'Charles Harris Garrigues']
cat2data_input_text : ['People from La Cañada Flintridge, California', '1891 births', 'American anti-communists', '20th-century American businesspeople', 'American newspaper publishers (people)', 'California Republicans', '1967 deaths', 'Businesspeople from Los Angeles', 'California Democrats']
cat2lbl2data_input_text : [['Los Angeles City Council members', '1898 births', 'California Republicans', '1967 deaths', '20th-century California politicians'], ['The San Diego Union-Tribune people', 'American male journalists', '20th-century American male writers', 'People from WaKeeney, Kansas', '1902 births', '1974 deaths', 'Writers from Kansas', 'People from Brentwood, Los Angeles', '20th-century American journalists', '20th-century American non-fiction writers']]

data_input_text : Lafayette B. Mendel House
lbl2data_input_text : ['National Register of Historic Places listings in New Haven, Connecticut', 'List of National Historic Landmarks in Connecticut']
cat2data_input_text : ['National Register of Historic Places in New Haven, Connecticut', 'Houses in New Haven, Connecticut', 'National Historic Landmarks in Connecticut', 'Houses on the National Register of Historic Places in Connecticut', 'Houses completed in 1858']
cat2lbl2data_input_text : [['History of New Haven, Connecticut', 'National Register of Historic Places in New Haven, Connecticut', 'Lists of National Register of Historic Places in Connecticut by populated place'], ['Lists of National Register of Historic Places in Connecticut', 'Lists of National Historic Landmarks by state', 'National Historic Landmarks in Connecticut']]

data_input_text : Ferriday Commercial Historic District
lbl2data_input_text : ['National Register of Historic Places listings in Concordia Parish, Louisiana']
cat2data_input_text : ['National Register of Historic Places in Concordia Parish, Louisiana', 'Italianate architecture in Louisiana', 'Historic districts on the National Register of Historic Places in Louisiana', 'Ferriday, Louisiana']
cat2lbl2data_input_text : [['National Register of Historic Places in Concordia Parish, Louisiana', 'Lists of National Register of Historic Places in Louisiana by parish']]

data_input_text : 1408 (film)
lbl2data_input_text : ['List of ghost films', 'Cell', 'List of adaptations of works by Stephen King']
cat2data_input_text : ['Films with screenplays by Scott Alexander and Larry Karaszewski', 'Di Bonaventura Pictures films', 'Films shot at Pinewood Studios', 'American supernatural horror films', '2000s horror thriller films', '2007 horror films', 'Films set in Manhattan', 'Films set in hotels', 'English-language horror thriller films', 'Films about writers', 'Films based on works by Stephen King', 'The Weinstein Company films', 'Films shot in London', 'Films directed by Mikael Håfström', 'American ghost films', 'Films about child death', 'Films produced by Lorenzo di Bonaventura', '2000s ghost films', '2000s psychological horror films', 'Films shot at Elstree Film Studios', 'Metro-Goldwyn-Mayer films', 'Films scored by Gabriel Yared', 'Fiction about haunted houses', '2000s American films', 'American horror thriller films', 'Films shot in New York City', 'Films based on American short stories', '2007 films', '2000s English-language films', 'Films shot in Los Angeles', 'American psychological horror films', 'Dimension Films films']
cat2lbl2data_input_text : [['Lists of horror films', 'Lists of films by topic', 'Television shows about ghosts', 'Ghost films', 'Lists of films by common content', 'Fictional ghosts'], [], ['Adaptations of works by Stephen King', 'Lists of films based on works', 'Lists of television series based on works']]

### `old-new-new`

In [ ]:
o = updated_show_func(x_prefix='old', y_prefix='new', z_prefix='new')

                               # Entries  # Features  \
Split Dataset
Train Main                        693082      573503
      Query Category Metadata     693082      872994
      Label Category Metadata     573503      872994
Test  Main                        177515      573503
      Query Category Metadata     177515      872994
      Label Category Metadata     573503      872994

                               Avg. Entries per feature  \
Split Dataset
Train Main                                         2.75
      Query Category Metadata                      4.16
      Label Category Metadata                      2.62
Test  Main                                         0.89
      Query Category Metadata                      1.03
      Label Category Metadata                      2.62

                               Avg. Feature per entry  \
Split Dataset
Train Main                                       2.28
      Query Category Metadata                    5.24
      Label Category Metadata                    3.98
Test  Main                                       2.88
      Query Category Metadata                    5.09
      Label Category Metadata                    3.98

                               Max. Entries per feature  \
Split Dataset
Train Main                                         2358
      Query Category Metadata                     36700
      Label Category Metadata                      7824
Test  Main                                          244
      Query Category Metadata                      6639
      Label Category Metadata                      7824

                               Max. Feature per entry  \
Split Dataset
Train Main                                        136
      Query Category Metadata                     245
      Label Category Metadata                     247
Test  Main                                        121
      Query Category Metadata                     247
      Label Category Metadata                     247

                               # Features without entry  \
Split Dataset
Train Main                                            0
      Query Category Metadata                    136111
      Label Category Metadata                    287010
Test  Main                                       296707
      Query Category Metadata                    526146
      Label Category Metadata                    287010

                               # Entries without feature
Split Dataset
Train Main                                         95940
      Query Category Metadata                      60302
      Label Category Metadata                     147334
Test  Main                                         28176
      Query Category Metadata                      13006
      Label Category Metadata                     147334

data_input_text : Certificate of Formula Compliance
lbl2data_input_text : ['Certificate of Origin']
cat2data_input_text : ['Cosmetic industry', 'International trade documents']
cat2lbl2data_input_text : [[]]

data_input_text : 2017 Sunwolves season
lbl2data_input_text : ['Sunwolves', '2017 Super Rugby season']
cat2data_input_text : ['2016–17 in Japanese rugby union', 'Sunwolves seasons', '2017–18 in Japanese rugby union', '2017 Super Rugby season by team']
cat2lbl2data_input_text : [['2020 disestablishments in Japan', 'Sunwolves', 'Rugby clubs established in 2015', '2015 establishments in Japan', 'Rugby union in Singapore', 'Rugby union clubs disestablished in 2020', 'Super Rugby teams', 'Rugby union teams in Tokyo'], ['2017 in Argentine rugby union', '2016–17 in Japanese rugby union', '2017 in Australian rugby union', '2017 rugby union tournaments for clubs', 'Super Rugby seasons', '2017 Super Rugby season', '2017 in New Zealand rugby union', '2017 in South African rugby union', '2017–18 in Japanese rugby union']]

data_input_text : Hadza people
lbl2data_input_text : ['Mbuti people', 'Baka people (Cameroon and Gabon)', 'Bongo people (Gabon)', 'Bushmen', '!Kung people', 'Aka people', 'Twa peoples']
cat2data_input_text : ['Hunter-gatherers of Africa', 'Indigenous peoples of East Africa', 'Ethnic groups in Tanzania']
cat2lbl2data_input_text : [['Ethnic groups in the Democratic Republic of the Congo', 'African Pygmies'], ['Ethnic groups in Cameroon', 'Ethnic groups in the Republic of the Congo', 'Ethnic groups in the Central African Republic', 'African Pygmies', 'Ethnic groups in Gabon', 'Modern nomads'], ['African Pygmies'], [], [], ['Modern nomads', 'African Pygmies', 'Ethnic groups in the Democratic Republic of the Congo', 'Ethnic groups in the Central African Republic'], []]

data_input_text : The Lost City (2005 film)
lbl2data_input_text : ['List of American films of 2005']
cat2data_input_text : ['Films about Jewish-American organized crime', 'Cultural depictions of Meyer Lansky', '2005 drama films', '2000s political drama films', 'Films set in Havana', 'Magnolia Pictures films', 'American political drama films', 'Films about the American Mafia', '2000s American films', 'Lionsgate films', 'Films shot in the Dominican Republic', '2005 films', 'Films set in 1958', 'Cultural depictions of Che Guevara']
cat2lbl2data_input_text : [['Lists of American films by year', '2005 in American cinema', 'Lists of 2005 films by country']]

data_input_text : Testability
lbl2data_input_text : ['Confirmability', 'Test method', 'Controllability', 'Observability', 'Scientific method']
cat2data_input_text : ['Empiricism', 'Logic', 'Observation', 'Scientific method', 'Philosophy of science']
cat2lbl2data_input_text : [[], ['Measurement', 'Tests', 'Metrology', 'Quality control'], ['Classical control theory'], ['Classical control theory'], ['Scientific method', 'Empiricism', 'Philosophy of science', 'Scientific Revolution']]

data_input_text : Veterans Memorial Parkway (Evansville)
lbl2data_input_text : []
cat2data_input_text : []
cat2lbl2data_input_text : []

data_input_text : Manchester Boddy
lbl2data_input_text : ['Charles E. Downs', 'C.H. Garrigues']
cat2data_input_text : ['People from La Cañada Flintridge, California', '1891 births', 'American anti-communists', '20th-century American businesspeople', 'American newspaper publishers (people)', 'California Republicans', '1967 deaths', 'Businesspeople from Los Angeles', 'California Democrats']
cat2lbl2data_input_text : [['Los Angeles City Council members', '1898 births', 'California Republicans', '1967 deaths', '20th-century California politicians'], []]

data_input_text : Lafayette B. Mendel House
lbl2data_input_text : ['List of National Historic Landmarks in Connecticut', 'National Register of Historic Places listings in New Haven, Connecticut']
cat2data_input_text : ['National Register of Historic Places in New Haven, Connecticut', 'Houses in New Haven, Connecticut', 'National Historic Landmarks in Connecticut', 'Houses on the National Register of Historic Places in Connecticut', 'Houses completed in 1858']
cat2lbl2data_input_text : [['Lists of National Register of Historic Places in Connecticut', 'Lists of National Historic Landmarks by state', 'National Historic Landmarks in Connecticut'], ['History of New Haven, Connecticut', 'National Register of Historic Places in New Haven, Connecticut', 'Lists of National Register of Historic Places in Connecticut by populated place']]

data_input_text : Ferriday Commercial Historic District
lbl2data_input_text : ['National Register of Historic Places listings in Concordia Parish, Louisiana']
cat2data_input_text : ['National Register of Historic Places in Concordia Parish, Louisiana', 'Italianate architecture in Louisiana', 'Historic districts on the National Register of Historic Places in Louisiana', 'Ferriday, Louisiana']
cat2lbl2data_input_text : [['National Register of Historic Places in Concordia Parish, Louisiana', 'Lists of National Register of Historic Places in Louisiana by parish']]

data_input_text : 1408 (film)
lbl2data_input_text : ['Silent Hill 4: The Room', 'List of ghost films', 'List of adaptations of works by Stephen King', 'Cell (film)']
cat2data_input_text : ['Films with screenplays by Scott Alexander and Larry Karaszewski', 'Di Bonaventura Pictures films', 'Films shot at Pinewood Studios', 'American supernatural horror films', '2000s horror thriller films', '2007 horror films', 'Films set in Manhattan', 'Films set in hotels', 'English-language horror thriller films', 'Films about writers', 'Films based on works by Stephen King', 'The Weinstein Company films', 'Films shot in London', 'Films directed by Mikael Håfström', 'American ghost films', 'Films about child death', 'Films produced by Lorenzo di Bonaventura', '2000s ghost films', '2000s psychological horror films', 'Films shot at Elstree Film Studios', 'Metro-Goldwyn-Mayer films', 'Films scored by Gabriel Yared', 'Fiction about haunted houses', '2000s American films', 'American horror thriller films', 'Films shot in New York City', 'Films based on American short stories', '2007 films', '2000s English-language films', 'Films shot in Los Angeles', 'American psychological horror films', 'Dimension Films films']
cat2lbl2data_input_text : [['Video games developed in Japan', '2004 video games', 'Single-player video games', 'Video games set in the United States', 'Survival horror video games', 'Video games about ghosts', 'Windows games', '2000s horror video games', 'Xbox games', 'Konami games', 'PlayStation 2 games', 'Video games scored by Akira Yamaoka', 'Psychological horror games', 'Silent Hill games'], ['Lists of horror films', 'Lists of films by topic', 'Television shows about ghosts', 'Ghost films', 'Lists of films by common content', 'Fictional ghosts'], ['Adaptations of works by Stephen King', 'Lists of films based on works', 'Lists of television series based on works'], ['Films about mobile phones', 'Saban Films films', 'English-language science fiction horror films', 'American horror television films', 'Films based on science fiction novels', '2010s science fiction horror films', 'Films directed by Tod Williams', '2016 thriller films', 'Films based on works by Stephen King', 'American science fiction thriller films', 'Films scored by Marcelo Zarvos', '2016 horror films', '2010s American films', 'Films shot in Atlanta', 'American science fiction horror films', '2016 films', 'Films based on American horror novels', '2010s English-language films', 'Films with screenplays by Stephen King', 'English-language thriller films']]

### `old-combined-new`

In [ ]:
o = updated_show_func(x_prefix='old', y_prefix='combined', z_prefix='new')

                               # Entries  # Features  \
Split Dataset
Train Main                        693082      646867
      Query Category Metadata     693082      885230
      Label Category Metadata     646867      885230
Test  Main                        177515      646867
      Query Category Metadata     177515      885230
      Label Category Metadata     646867      885230

                               Avg. Entries per feature  \
Split Dataset
Train Main                                         3.24
      Query Category Metadata                      4.10
      Label Category Metadata                      2.89
Test  Main                                         1.11
      Query Category Metadata                      1.02
      Label Category Metadata                      2.89

                               Avg. Feature per entry  \
Split Dataset
Train Main                                       3.02
      Query Category Metadata                    5.24
      Label Category Metadata                    3.96
Test  Main                                       4.04
      Query Category Metadata                    5.11
      Label Category Metadata                    3.96

                               Max. Entries per feature  \
Split Dataset
Train Main                                         2745
      Query Category Metadata                     36700
      Label Category Metadata                      8650
Test  Main                                          310
      Query Category Metadata                      6639
      Label Category Metadata                      8650

                               Max. Feature per entry  \
Split Dataset
Train Main                                        137
      Query Category Metadata                     245
      Label Category Metadata                     247
Test  Main                                        153
      Query Category Metadata                     247
      Label Category Metadata                     247

                               # Features without entry  \
Split Dataset
Train Main                                            0
      Query Category Metadata                    148347
      Label Category Metadata                    265110
Test  Main                                       267586
      Query Category Metadata                    534527
      Label Category Metadata                    265110

                               # Entries without feature
Split Dataset
Train Main                                          8199
      Query Category Metadata                      60302
      Label Category Metadata                     171199
Test  Main                                           768
      Query Category Metadata                      12898
      Label Category Metadata                     171199

data_input_text : Certificate of Formula Compliance
lbl2data_input_text : ['Certificate of Origin', 'Certificate of origin']
cat2data_input_text : ['Cosmetic industry', 'International trade documents']
cat2lbl2data_input_text : [[], ['Export', 'International trade documents']]

data_input_text : 2017 Sunwolves season
lbl2data_input_text : ['2017 Super Rugby season', 'Sunwolves']
cat2data_input_text : ['2016–17 in Japanese rugby union', 'Sunwolves seasons', '2017–18 in Japanese rugby union', '2017 Super Rugby season by team']
cat2lbl2data_input_text : [['2017 in Argentine rugby union', '2016–17 in Japanese rugby union', '2017 in Australian rugby union', '2017 rugby union tournaments for clubs', 'Super Rugby seasons', '2017 Super Rugby season', '2017 in New Zealand rugby union', '2017 in South African rugby union', '2017–18 in Japanese rugby union'], ['2020 disestablishments in Japan', 'Sunwolves', 'Rugby clubs established in 2015', '2015 establishments in Japan', 'Rugby union in Singapore', 'Rugby union clubs disestablished in 2020', 'Super Rugby teams', 'Rugby union teams in Tokyo']]

data_input_text : Hadza people
lbl2data_input_text : ['Mbuti people', 'Baka people (Cameroon and Gabon)', 'Bongo people (Gabon)', 'Bushmen', '!Kung people', 'Aka people', 'Twa peoples', 'San people', 'Twa']
cat2data_input_text : ['Hunter-gatherers of Africa', 'Indigenous peoples of East Africa', 'Ethnic groups in Tanzania']
cat2lbl2data_input_text : [['Ethnic groups in the Democratic Republic of the Congo', 'African Pygmies'], ['Ethnic groups in Cameroon', 'Ethnic groups in the Republic of the Congo', 'Ethnic groups in the Central African Republic', 'African Pygmies', 'Ethnic groups in Gabon', 'Modern nomads'], ['African Pygmies'], [], [], ['Modern nomads', 'African Pygmies', 'Ethnic groups in the Democratic Republic of the Congo', 'Ethnic groups in the Central African Republic'], [], ['Hunter-gatherers of Africa', 'African nomads', 'Ethnic groups in Zimbabwe', 'Ethnic groups in Botswana', 'Coloureds', 'Indigenous peoples of Southern Africa', 'San people', 'Ethnic groups in Namibia', 'Ethnic groups in Angola'], ['Ethnic groups in Zambia', 'Ethnic groups in Botswana', 'Ethnic groups in the Democratic Republic of the Congo', 'African Pygmies', 'Ethnic groups in Namibia', 'Ethnic groups in Angola']]

data_input_text : The Lost City (2005 film)
lbl2data_input_text : ['List of American films of 2005']
cat2data_input_text : ['Films about Jewish-American organized crime', 'Cultural depictions of Meyer Lansky', '2005 drama films', '2000s political drama films', 'Films set in Havana', 'Magnolia Pictures films', 'American political drama films', 'Films about the American Mafia', '2000s American films', 'Lionsgate films', 'Films shot in the Dominican Republic', '2005 films', 'Films set in 1958', 'Cultural depictions of Che Guevara']
cat2lbl2data_input_text : [['Lists of American films by year', '2005 in American cinema', 'Lists of 2005 films by country']]

data_input_text : Testability
lbl2data_input_text : ['Scientific method', 'Testability', 'Observability', 'Test method', 'Controllability', 'Confirmability', 'Contingency']
cat2data_input_text : ['Empiricism', 'Logic', 'Observation', 'Scientific method', 'Philosophy of science']
cat2lbl2data_input_text : [['Scientific method', 'Empiricism', 'Philosophy of science', 'Scientific Revolution'], ['Empiricism', 'Logic', 'Observation', 'Scientific method', 'Philosophy of science'], ['Classical control theory'], ['Measurement', 'Tests', 'Metrology', 'Quality control'], ['Classical control theory'], [], []]

data_input_text : Veterans Memorial Parkway (Evansville)
lbl2data_input_text : ['Indiana']
cat2data_input_text : []
cat2lbl2data_input_text : [['States and territories established in 1816', 'States of the United States', 'Midwestern United States', 'Indiana', 'Articles containing video clips', '1816 establishments in the United States', 'Contiguous United States']]

data_input_text : Manchester Boddy
lbl2data_input_text : ['Charles E. Downs', 'C.H. Garrigues', 'Charles Harris Garrigues']
cat2data_input_text : ['People from La Cañada Flintridge, California', '1891 births', 'American anti-communists', '20th-century American businesspeople', 'American newspaper publishers (people)', 'California Republicans', '1967 deaths', 'Businesspeople from Los Angeles', 'California Democrats']
cat2lbl2data_input_text : [['Los Angeles City Council members', '1898 births', 'California Republicans', '1967 deaths', '20th-century California politicians'], [], ['The San Diego Union-Tribune people', 'American male journalists', '20th-century American male writers', 'People from WaKeeney, Kansas', '1902 births', '1974 deaths', 'Writers from Kansas', 'People from Brentwood, Los Angeles', '20th-century American journalists', '20th-century American non-fiction writers']]

data_input_text : Lafayette B. Mendel House
lbl2data_input_text : ['National Register of Historic Places listings in New Haven, Connecticut', 'List of National Historic Landmarks in Connecticut']
cat2data_input_text : ['National Register of Historic Places in New Haven, Connecticut', 'Houses in New Haven, Connecticut', 'National Historic Landmarks in Connecticut', 'Houses on the National Register of Historic Places in Connecticut', 'Houses completed in 1858']
cat2lbl2data_input_text : [['History of New Haven, Connecticut', 'National Register of Historic Places in New Haven, Connecticut', 'Lists of National Register of Historic Places in Connecticut by populated place'], ['Lists of National Register of Historic Places in Connecticut', 'Lists of National Historic Landmarks by state', 'National Historic Landmarks in Connecticut']]

data_input_text : Ferriday Commercial Historic District
lbl2data_input_text : ['National Register of Historic Places listings in Concordia Parish, Louisiana']
cat2data_input_text : ['National Register of Historic Places in Concordia Parish, Louisiana', 'Italianate architecture in Louisiana', 'Historic districts on the National Register of Historic Places in Louisiana', 'Ferriday, Louisiana']
cat2lbl2data_input_text : [['National Register of Historic Places in Concordia Parish, Louisiana', 'Lists of National Register of Historic Places in Louisiana by parish']]

data_input_text : 1408 (film)
lbl2data_input_text : ['List of ghost films', 'List of adaptations of works by Stephen King', 'Silent Hill 4: The Room', 'Cell (film)', 'Cell']
cat2data_input_text : ['Films with screenplays by Scott Alexander and Larry Karaszewski', 'Di Bonaventura Pictures films', 'Films shot at Pinewood Studios', 'American supernatural horror films', '2000s horror thriller films', '2007 horror films', 'Films set in Manhattan', 'Films set in hotels', 'English-language horror thriller films', 'Films about writers', 'Films based on works by Stephen King', 'The Weinstein Company films', 'Films shot in London', 'Films directed by Mikael Håfström', 'American ghost films', 'Films about child death', 'Films produced by Lorenzo di Bonaventura', '2000s ghost films', '2000s psychological horror films', 'Films shot at Elstree Film Studios', 'Metro-Goldwyn-Mayer films', 'Films scored by Gabriel Yared', 'Fiction about haunted houses', '2000s American films', 'American horror thriller films', 'Films shot in New York City', 'Films based on American short stories', '2007 films', '2000s English-language films', 'Films shot in Los Angeles', 'American psychological horror films', 'Dimension Films films']
cat2lbl2data_input_text : [['Lists of horror films', 'Lists of films by topic', 'Television shows about ghosts', 'Ghost films', 'Lists of films by common content', 'Fictional ghosts'], ['Adaptations of works by Stephen King', 'Lists of films based on works', 'Lists of television series based on works'], ['Video games developed in Japan', '2004 video games', 'Single-player video games', 'Video games set in the United States', 'Survival horror video games', 'Video games about ghosts', 'Windows games', '2000s horror video games', 'Xbox games', 'Konami games', 'PlayStation 2 games', 'Video games scored by Akira Yamaoka', 'Psychological horror games', 'Silent Hill games'], ['Films about mobile phones', 'Saban Films films', 'English-language science fiction horror films', 'American horror television films', 'Films based on science fiction novels', '2010s science fiction horror films', 'Films directed by Tod Williams', '2016 thriller films', 'Films based on works by Stephen King', 'American science fiction thriller films', 'Films scored by Marcelo Zarvos', '2016 horror films', '2010s American films', 'Films shot in Atlanta', 'American science fiction horror films', '2016 films', 'Films based on American horror novels', '2010s English-language films', 'Films with screenplays by Stephen King', 'English-language thriller films'], []]

### `old-old-combined`

In [ ]:
o = updated_show_func(x_prefix='old', y_prefix='old', z_prefix='combined')

                               # Entries  # Features  \
Split Dataset
Train Main                        693082      312330
      Query Category Metadata     693082      922126
      Label Category Metadata     312330      922126
Test  Main                        177515      312330
      Query Category Metadata     177515      922126
      Label Category Metadata     312330      922126

                               Avg. Entries per feature  \
Split Dataset
Train Main                                         4.67
      Query Category Metadata                      5.01
      Label Category Metadata                      1.93
Test  Main                                         1.73
      Query Category Metadata                      1.22
      Label Category Metadata                      1.93

                               Avg. Feature per entry  \
Split Dataset
Train Main                                       2.11
      Query Category Metadata                    6.66
      Label Category Metadata                    5.69
Test  Main                                       3.05
      Query Category Metadata                    6.35
      Label Category Metadata                    5.69

                               Max. Entries per feature  \
Split Dataset
Train Main                                         2929
      Query Category Metadata                     44772
      Label Category Metadata                      3904
Test  Main                                          309
      Query Category Metadata                      7938
      Label Category Metadata                      3904

                               Max. Feature per entry  \
Split Dataset
Train Main                                         57
      Query Category Metadata                     287
      Label Category Metadata                     287
Test  Main                                        129
      Query Category Metadata                     256
      Label Category Metadata                     287

                               # Features without entry  \
Split Dataset
Train Main                                            0
      Query Category Metadata                     74549
      Label Category Metadata                    450652
Test  Main                                            0
      Query Category Metadata                    524961
      Label Category Metadata                    450652

                               # Entries without feature
Split Dataset
Train Main                                             0
      Query Category Metadata                       2684
      Label Category Metadata                      22467
Test  Main                                             0
      Query Category Metadata                       1524
      Label Category Metadata                      22467

data_input_text : Certificate of Formula Compliance
lbl2data_input_text : ['Certificate of origin']
cat2data_input_text : ['International trade documents', 'Cosmetic industry']
cat2lbl2data_input_text : [['Export', 'International trade documents']]

data_input_text : 2017 Sunwolves season
lbl2data_input_text : ['Sunwolves', '2017 Super Rugby season']
cat2data_input_text : ['2016–17 in Japanese rugby union', 'Sunwolves seasons', '2017–18 in Japanese rugby union', '2017 Super Rugby season by team', '2016â\x80\x9317 in Japanese rugby union', '2017â\x80\x9318 in Japanese rugby union']
cat2lbl2data_input_text : [['Sunwolves', '2020 disestablishments in Japan', 'Rugby clubs established in 2015', '2015 establishments in Japan', 'Rugby union in Singapore', 'Rugby union clubs disestablished in 2020', 'Super Rugby teams', 'Rugby union teams in Tokyo', 'Sports teams in Tokyo'], ['2017 Super Rugby season', '2017 in South African rugby union', '2017 rugby union tournaments for clubs', 'Super Rugby seasons', '2016–17 in Japanese rugby union', '2017–18 in Japanese rugby union', '2017 in Argentine rugby union', '2017 in Australian rugby union', '2017 in New Zealand rugby union', '2016â\x80\x9317 in Japanese rugby union', '2017â\x80\x9318 in Japanese rugby union']]

data_input_text : Hadza people
lbl2data_input_text : ['Twa', 'Aka people', 'San people']
cat2data_input_text : ['Ethnic groups in Tanzania', 'Indigenous peoples of East Africa', 'Hunter-gatherers of Africa']
cat2lbl2data_input_text : [['Ethnic groups in Zambia', 'Ethnic groups in the Democratic Republic of the Congo', 'Ethnic groups in Namibia', 'Ethnic groups in Angola', 'African Pygmies', 'Ethnic groups in Botswana'], ['Modern nomads', 'Ethnic groups in the Democratic Republic of the Congo', 'African Pygmies', 'Ethnic groups in the Central African Republic'], ['San people', 'Hunter-gatherers of Africa', 'African nomads', 'Ethnic groups in Namibia', 'Ethnic groups in Angola', 'Coloureds', 'Ethnic groups in Botswana', 'Indigenous peoples of Southern Africa', 'Ethnic groups in Zimbabwe']]

data_input_text : The Lost City (2005 film)
lbl2data_input_text : ['List of American films of 2005']
cat2data_input_text : ['2000s American films', '2005 films', 'Lionsgate films', 'Films set in 1958', 'Films about Jewish-American organized crime', '2005 drama films', 'Films about the American Mafia', 'American political drama films', 'Mafia films', 'Cultural depictions of Che Guevara', '2000s political drama films', 'Magnolia Pictures films', 'Films set in Cuba', 'Cultural depictions of Meyer Lansky', 'Films set in Havana', 'Films shot in the Dominican Republic', 'American films', '2000s drama films', 'Lions Gate Entertainment films']
cat2lbl2data_input_text : [['Lists of American films by year', 'Lists of 2005 films by country', '2005 in American cinema', 'Lists of 2005 films by country or language']]

data_input_text : Testability
lbl2data_input_text : ['Scientific method', 'Contingency', 'Testability', 'Observability', 'Controllability']
cat2data_input_text : ['Logic', 'Philosophy of science', 'Empiricism', 'Scientific method', 'Observation']
cat2lbl2data_input_text : [['Philosophy of science', 'Empiricism', 'Scientific method', 'Scientific Revolution', 'Scientific revolution'], [], ['Logic', 'Philosophy of science', 'Empiricism', 'Scientific method', 'Observation'], ['Classical control theory'], ['Classical control theory']]

data_input_text : Veterans Memorial Parkway (Evansville)
lbl2data_input_text : ['Numbered highways in the United States', 'Indiana']
cat2data_input_text : ['Parkways in the United States', 'Transportation in Evansville, Indiana', 'Transportation in Vanderburgh County, Indiana', 'Roads in Indiana']
cat2lbl2data_input_text : [['Road signs in the United States', 'Highways in the United States', 'United States state insignia', 'State highways in the United States'], ['Articles containing video clips', 'States and territories established in 1816', 'States of the United States', 'Midwestern United States', 'Contiguous United States', 'Indiana', '1816 establishments in the United States', 'U.S. states with multiple time zones']]

data_input_text : Manchester Boddy
lbl2data_input_text : ['Charles E. Downs', 'Charles Harris Garrigues']
cat2data_input_text : ['1891 births', '20th-century American businesspeople', '1967 deaths', 'California Democrats', 'California Republicans', 'American newspaper publishers (people)', 'American anti-communists', 'Businesspeople from Los Angeles', 'People from La Cañada Flintridge, California', 'People from La CaÃ±ada Flintridge, California']
cat2lbl2data_input_text : [['1898 births', '1967 deaths', 'California Republicans', '20th-century American politicians', '20th-century California politicians', 'Los Angeles City Council members'], ['20th-century American male writers', '20th-century American non-fiction writers', 'American male journalists', '20th-century American journalists', '1902 births', '1974 deaths', 'People from Brentwood, Los Angeles', 'The San Diego Union-Tribune people', 'People from WaKeeney, Kansas', 'Writers from Kansas']]

data_input_text : Lafayette B. Mendel House
lbl2data_input_text : ['National Register of Historic Places listings in New Haven, Connecticut', 'List of National Historic Landmarks in Connecticut']
cat2data_input_text : ['Houses on the National Register of Historic Places in Connecticut', 'Houses completed in 1858', 'National Register of Historic Places in New Haven, Connecticut', 'National Historic Landmarks in Connecticut', 'Houses in New Haven, Connecticut']
cat2lbl2data_input_text : [['National Register of Historic Places in New Haven, Connecticut', 'History of New Haven, Connecticut', 'Lists of National Register of Historic Places in Connecticut by populated place', 'Lists of National Register of Historic Places in Connecticut by city'], ['Lists of National Historic Landmarks by state', 'Connecticut-related lists', 'National Historic Landmarks in Connecticut', 'Lists of National Register of Historic Places in Connecticut']]

data_input_text : Ferriday Commercial Historic District
lbl2data_input_text : ['National Register of Historic Places listings in Concordia Parish, Louisiana']
cat2data_input_text : ['National Register of Historic Places in Concordia Parish, Louisiana', 'Italianate architecture in Louisiana', 'Historic districts on the National Register of Historic Places in Louisiana', 'Ferriday, Louisiana', 'Concordia Parish, Louisiana']
cat2lbl2data_input_text : [['Lists of National Register of Historic Places in Louisiana by parish', 'National Register of Historic Places in Concordia Parish, Louisiana']]

data_input_text : 1408 (film)
lbl2data_input_text : ['List of ghost films', 'Cell', 'List of adaptations of works by Stephen King']
cat2data_input_text : ['Films about writers', 'Films shot in Los Angeles', '2000s American films', '2007 films', '2000s English-language films', 'English-language horror thriller films', 'Metro-Goldwyn-Mayer films', 'American supernatural horror films', 'Films based on American short stories', 'American ghost films', 'American horror thriller films', 'Films shot in New York City', 'Films shot at Pinewood Studios', 'Films shot at Elstree Film Studios', 'Films set in hotels', '2007 horror films', 'Films based on short fiction', 'Films scored by Gabriel Yared', '2000s ghost films', 'Films shot in London', '2000s horror thriller films', 'Films set in Manhattan', 'Films about child death', 'Dimension Films films', 'American psychological horror films', 'The Weinstein Company films', '2000s psychological horror films', 'Films directed by Mikael Håfström', 'Films based on works by Stephen King', 'Fiction about haunted houses', 'Films with screenplays by Scott Alexander and Larry Karaszewski', 'Di Bonaventura Pictures films', 'Films produced by Lorenzo di Bonaventura', 'Films shot at Elstree Studios', 'American films', 'Films directed by Mikael HÃ¥fstrÃ¶m', 'Screenplays by Scott Alexander and Larry Karaszewski']
cat2lbl2data_input_text : [['Lists of films by common content', 'Fictional ghosts', 'Thrillers', 'Lists of films by topic', 'Lists of horror films', 'Television shows about ghosts', 'Ghost films', 'Ghosts in television', 'Suspense'], [], ['Lists of television series based on works', 'Lists of films based on works', 'Adaptations of works by Stephen King']]

### `old-new-combined`

In [ ]:
o = updated_show_func(x_prefix='old', y_prefix='new', z_prefix='combined')

                               # Entries  # Features  \
Split Dataset
Train Main                        693082      573503
      Query Category Metadata     693082      983819
      Label Category Metadata     573503      983819
Test  Main                        177515      573503
      Query Category Metadata     177515      983819
      Label Category Metadata     573503      983819

                               Avg. Entries per feature  \
Split Dataset
Train Main                                         2.75
      Query Category Metadata                      4.69
      Label Category Metadata                      2.52
Test  Main                                         0.89
      Query Category Metadata                      1.16
      Label Category Metadata                      2.52

                               Avg. Feature per entry  \
Split Dataset
Train Main                                       2.28
      Query Category Metadata                    6.66
      Label Category Metadata                    4.31
Test  Main                                       2.88
      Query Category Metadata                    6.41
      Label Category Metadata                    4.31

                               Max. Entries per feature  \
Split Dataset
Train Main                                         2358
      Query Category Metadata                     44772
      Label Category Metadata                      8088
Test  Main                                          244
      Query Category Metadata                      7938
      Label Category Metadata                      8088

                               Max. Feature per entry  \
Split Dataset
Train Main                                        136
      Query Category Metadata                     287
      Label Category Metadata                     287
Test  Main                                        121
      Query Category Metadata                     256
      Label Category Metadata                     287

                               # Features without entry  \
Split Dataset
Train Main                                            0
      Query Category Metadata                    136198
      Label Category Metadata                    361763
Test  Main                                       296707
      Query Category Metadata                    576924
      Label Category Metadata                    361763

                               # Entries without feature
Split Dataset
Train Main                                         95940
      Query Category Metadata                       2684
      Label Category Metadata                     147061
Test  Main                                         28176
      Query Category Metadata                       1386
      Label Category Metadata                     147061

data_input_text : Certificate of Formula Compliance
lbl2data_input_text : ['Certificate of Origin']
cat2data_input_text : ['International trade documents', 'Cosmetic industry']
cat2lbl2data_input_text : [[]]

data_input_text : 2017 Sunwolves season
lbl2data_input_text : ['Sunwolves', '2017 Super Rugby season']
cat2data_input_text : ['2016–17 in Japanese rugby union', 'Sunwolves seasons', '2017–18 in Japanese rugby union', '2017 Super Rugby season by team', '2016â\x80\x9317 in Japanese rugby union', '2017â\x80\x9318 in Japanese rugby union']
cat2lbl2data_input_text : [['Sunwolves', '2020 disestablishments in Japan', 'Rugby clubs established in 2015', '2015 establishments in Japan', 'Rugby union in Singapore', 'Rugby union clubs disestablished in 2020', 'Super Rugby teams', 'Rugby union teams in Tokyo', 'Sports teams in Tokyo'], ['2017 Super Rugby season', '2017 in South African rugby union', '2017 rugby union tournaments for clubs', 'Super Rugby seasons', '2016–17 in Japanese rugby union', '2017–18 in Japanese rugby union', '2017 in Argentine rugby union', '2017 in Australian rugby union', '2017 in New Zealand rugby union', '2016â\x80\x9317 in Japanese rugby union', '2017â\x80\x9318 in Japanese rugby union']]

data_input_text : Hadza people
lbl2data_input_text : ['Mbuti people', 'Baka people (Cameroon and Gabon)', 'Bongo people (Gabon)', 'Bushmen', '!Kung people', 'Aka people', 'Twa peoples']
cat2data_input_text : ['Ethnic groups in Tanzania', 'Indigenous peoples of East Africa', 'Hunter-gatherers of Africa']
cat2lbl2data_input_text : [['Ethnic groups in the Democratic Republic of the Congo', 'African Pygmies'], ['Modern nomads', 'African Pygmies', 'Ethnic groups in the Central African Republic', 'Ethnic groups in the Republic of the Congo', 'Ethnic groups in Gabon', 'Ethnic groups in Cameroon'], ['African Pygmies'], [], [], ['Modern nomads', 'Ethnic groups in the Democratic Republic of the Congo', 'African Pygmies', 'Ethnic groups in the Central African Republic', 'Modern_nomads'], []]

data_input_text : The Lost City (2005 film)
lbl2data_input_text : ['List of American films of 2005']
cat2data_input_text : ['2000s American films', '2005 films', 'Lionsgate films', 'Films set in 1958', 'Films about Jewish-American organized crime', '2005 drama films', 'Films about the American Mafia', 'American political drama films', 'Mafia films', 'Cultural depictions of Che Guevara', '2000s political drama films', 'Magnolia Pictures films', 'Films set in Cuba', 'Cultural depictions of Meyer Lansky', 'Films set in Havana', 'Films shot in the Dominican Republic', '2000s drama films', 'American films', 'Lions Gate Entertainment films']
cat2lbl2data_input_text : [['Lists of American films by year', 'Lists of 2005 films by country', '2005 in American cinema', 'Lists of 2005 films by country or language']]

data_input_text : Testability
lbl2data_input_text : ['Confirmability', 'Test method', 'Controllability', 'Observability', 'Scientific method']
cat2data_input_text : ['Logic', 'Philosophy of science', 'Empiricism', 'Scientific method', 'Observation']
cat2lbl2data_input_text : [[], ['Quality control', 'Measurement', 'Tests', 'Metrology'], ['Classical control theory'], ['Classical control theory'], ['Philosophy of science', 'Empiricism', 'Scientific method', 'Scientific Revolution']]

data_input_text : Veterans Memorial Parkway (Evansville)
lbl2data_input_text : []
cat2data_input_text : ['Parkways in the United States', 'Transportation in Evansville, Indiana', 'Transportation in Vanderburgh County, Indiana', 'Roads in Indiana']
cat2lbl2data_input_text : []

data_input_text : Manchester Boddy
lbl2data_input_text : ['Charles E. Downs', 'C.H. Garrigues']
cat2data_input_text : ['1891 births', '20th-century American businesspeople', '1967 deaths', 'California Democrats', 'American anti-communists', 'California Republicans', 'Businesspeople from Los Angeles', 'American newspaper publishers (people)', 'People from La Cañada Flintridge, California', 'People from La CaÃ±ada Flintridge, California']
cat2lbl2data_input_text : [['1898 births', '1967 deaths', 'California Republicans', '20th-century American politicians', '20th-century California politicians', 'Los Angeles City Council members'], []]

data_input_text : Lafayette B. Mendel House
lbl2data_input_text : ['List of National Historic Landmarks in Connecticut', 'National Register of Historic Places listings in New Haven, Connecticut']
cat2data_input_text : ['Houses on the National Register of Historic Places in Connecticut', 'Houses completed in 1858', 'National Register of Historic Places in New Haven, Connecticut', 'National Historic Landmarks in Connecticut', 'Houses in New Haven, Connecticut']
cat2lbl2data_input_text : [['Lists of National Historic Landmarks by state', 'Connecticut-related lists', 'National Historic Landmarks in Connecticut', 'Lists of National Register of Historic Places in Connecticut'], ['National Register of Historic Places in New Haven, Connecticut', 'History of New Haven, Connecticut', 'Lists of National Register of Historic Places in Connecticut by populated place', 'Lists of National Register of Historic Places in Connecticut by city']]

data_input_text : Ferriday Commercial Historic District
lbl2data_input_text : ['National Register of Historic Places listings in Concordia Parish, Louisiana']
cat2data_input_text : ['National Register of Historic Places in Concordia Parish, Louisiana', 'Italianate architecture in Louisiana', 'Historic districts on the National Register of Historic Places in Louisiana', 'Ferriday, Louisiana', 'Concordia Parish, Louisiana']
cat2lbl2data_input_text : [['Lists of National Register of Historic Places in Louisiana by parish', 'National Register of Historic Places in Concordia Parish, Louisiana']]

data_input_text : 1408 (film)
lbl2data_input_text : ['Silent Hill 4: The Room', 'List of ghost films', 'List of adaptations of works by Stephen King', 'Cell (film)']
cat2data_input_text : ['Films about writers', '2000s American films', '2000s English-language films', 'Films shot in Los Angeles', '2007 films', 'English-language horror thriller films', 'Metro-Goldwyn-Mayer films', 'American supernatural horror films', 'Films based on American short stories', 'American ghost films', 'American horror thriller films', 'Films shot in New York City', 'Films shot at Pinewood Studios', 'Films shot at Elstree Film Studios', 'Films set in hotels', '2007 horror films', 'Films based on short fiction', 'Films scored by Gabriel Yared', 'Films set in Manhattan', '2000s ghost films', 'Films shot in London', '2000s horror thriller films', 'The Weinstein Company films', 'Films about child death', 'Dimension Films films', 'American psychological horror films', '2000s psychological horror films', 'Films based on works by Stephen King', 'Films directed by Mikael Håfström', 'Fiction about haunted houses', 'Films with screenplays by Scott Alexander and Larry Karaszewski', 'Di Bonaventura Pictures films', 'Films produced by Lorenzo di Bonaventura', 'Films shot at Elstree Studios', 'American films', 'Films directed by Mikael HÃ¥fstrÃ¶m', 'Screenplays by Scott Alexander and Larry Karaszewski']
cat2lbl2data_input_text : [['Video games developed in Japan', 'Windows games', '2004 video games', 'Single-player video games', 'Video games about ghosts', 'Video games set in the United States', 'Xbox games', 'Psychological horror games', 'PlayStation 2 games', 'Konami games', '2000s horror video games', 'Video games scored by Akira Yamaoka', 'Survival horror video games', 'Silent Hill games'], ['Lists of films by common content', 'Fictional ghosts', 'Lists of films by topic', 'Lists of horror films', 'Television shows about ghosts', 'Ghost films'], ['Lists of television series based on works', 'Lists of films based on works', 'Adaptations of works by Stephen King'], ['2010s English-language films', '2010s American films', 'English-language science fiction horror films', 'American science fiction horror films', 'English-language thriller films', '2016 films', 'American science fiction thriller films', 'American horror television films', 'Films based on science fiction novels', 'Films shot in Atlanta', 'Films based on American horror novels', 'Films with screenplays by Stephen King', '2016 horror films', '2016 thriller films', '2010s science fiction horror films', 'Films scored by Marcelo Zarvos', 'Films based on works by Stephen King', 'Films directed by Tod Williams', 'Films about mobile phones', 'Saban Films films']]

### `old-combined-combined`

In [ ]:
o = updated_show_func(x_prefix='old', y_prefix='combined', z_prefix='combined')

                               # Entries  # Features  \
Split Dataset
Train Main                        693082      646867
      Query Category Metadata     693082      991035
      Label Category Metadata     646867      991035
Test  Main                        177515      646867
      Query Category Metadata     177515      991035
      Label Category Metadata     646867      991035

                               Avg. Entries per feature  \
Split Dataset
Train Main                                         3.24
      Query Category Metadata                      4.66
      Label Category Metadata                      2.83
Test  Main                                         1.11
      Query Category Metadata                      1.15
      Label Category Metadata                      2.83

                               Avg. Feature per entry  \
Split Dataset
Train Main                                       3.02
      Query Category Metadata                    6.66
      Label Category Metadata                    4.34
Test  Main                                       4.04
      Query Category Metadata                    6.42
      Label Category Metadata                    4.34

                               Max. Entries per feature  \
Split Dataset
Train Main                                         2745
      Query Category Metadata                     44772
      Label Category Metadata                      9066
Test  Main                                          310
      Query Category Metadata                      7938
      Label Category Metadata                      9066

                               Max. Feature per entry  \
Split Dataset
Train Main                                        137
      Query Category Metadata                     287
      Label Category Metadata                     287
Test  Main                                        153
      Query Category Metadata                     256
      Label Category Metadata                     287

                               # Features without entry  \
Split Dataset
Train Main                                            0
      Query Category Metadata                    143410
      Label Category Metadata                    328328
Test  Main                                       267586
      Query Category Metadata                    581799
      Label Category Metadata                    328328

                               # Entries without feature
Split Dataset
Train Main                                          8199
      Query Category Metadata                       2684
      Label Category Metadata                     168032
Test  Main                                           768
      Query Category Metadata                       1371
      Label Category Metadata                     168032

data_input_text : Certificate of Formula Compliance
lbl2data_input_text : ['Certificate of Origin', 'Certificate of origin']
cat2data_input_text : ['International trade documents', 'Cosmetic industry']
cat2lbl2data_input_text : [[], ['Export', 'International trade documents']]

data_input_text : 2017 Sunwolves season
lbl2data_input_text : ['2017 Super Rugby season', 'Sunwolves']
cat2data_input_text : ['2016–17 in Japanese rugby union', 'Sunwolves seasons', '2017–18 in Japanese rugby union', '2017 Super Rugby season by team', '2016â\x80\x9317 in Japanese rugby union', '2017â\x80\x9318 in Japanese rugby union']
cat2lbl2data_input_text : [['2017 Super Rugby season', '2017 in South African rugby union', '2017 rugby union tournaments for clubs', 'Super Rugby seasons', '2016–17 in Japanese rugby union', '2017–18 in Japanese rugby union', '2017 in Argentine rugby union', '2017 in Australian rugby union', '2017 in New Zealand rugby union', '2016â\x80\x9317 in Japanese rugby union', '2017â\x80\x9318 in Japanese rugby union'], ['Sunwolves', '2020 disestablishments in Japan', 'Rugby clubs established in 2015', '2015 establishments in Japan', 'Rugby union in Singapore', 'Rugby union clubs disestablished in 2020', 'Super Rugby teams', 'Rugby union teams in Tokyo', 'Sports teams in Tokyo']]

data_input_text : Hadza people
lbl2data_input_text : ['Mbuti people', 'Baka people (Cameroon and Gabon)', 'Bongo people (Gabon)', 'Bushmen', '!Kung people', 'Aka people', 'Twa peoples', 'San people', 'Twa']
cat2data_input_text : ['Ethnic groups in Tanzania', 'Indigenous peoples of East Africa', 'Hunter-gatherers of Africa']
cat2lbl2data_input_text : [['Ethnic groups in the Democratic Republic of the Congo', 'African Pygmies'], ['Modern nomads', 'African Pygmies', 'Ethnic groups in the Central African Republic', 'Ethnic groups in the Republic of the Congo', 'Ethnic groups in Gabon', 'Ethnic groups in Cameroon'], ['African Pygmies'], [], [], ['Modern nomads', 'Ethnic groups in the Democratic Republic of the Congo', 'African Pygmies', 'Ethnic groups in the Central African Republic', 'Modern_nomads'], [], ['Indigenous peoples of Southern Africa', 'San people', 'Hunter-gatherers of Africa', 'African nomads', 'Ethnic groups in Namibia', 'Ethnic groups in Angola', 'Coloureds', 'Ethnic groups in South Africa', 'Ethnic groups in Botswana', 'Ethnic groups in Zimbabwe'], ['Ethnic groups in Zambia', 'Ethnic groups in the Democratic Republic of the Congo', 'Ethnic groups in Namibia', 'Ethnic groups in Angola', 'African Pygmies', 'Ethnic groups in Botswana']]

data_input_text : The Lost City (2005 film)
lbl2data_input_text : ['List of American films of 2005']
cat2data_input_text : ['2000s American films', '2005 films', 'Lionsgate films', 'Films set in 1958', 'Films about Jewish-American organized crime', '2005 drama films', 'Films about the American Mafia', 'American political drama films', 'Mafia films', 'Cultural depictions of Che Guevara', '2000s political drama films', 'Magnolia Pictures films', 'Films set in Cuba', 'Cultural depictions of Meyer Lansky', 'Films set in Havana', 'Films shot in the Dominican Republic', '2000s drama films', 'American films', 'Lions Gate Entertainment films']
cat2lbl2data_input_text : [['Lists of American films by year', 'Lists of 2005 films by country', '2005 in American cinema', 'Lists of 2005 films by country or language']]

data_input_text : Testability
lbl2data_input_text : ['Scientific method', 'Testability', 'Observability', 'Test method', 'Controllability', 'Confirmability', 'Contingency']
cat2data_input_text : ['Logic', 'Philosophy of science', 'Empiricism', 'Scientific method', 'Observation']
cat2lbl2data_input_text : [['Philosophy of science', 'Empiricism', 'Scientific method', 'Scientific Revolution'], ['Logic', 'Philosophy of science', 'Empiricism', 'Scientific method', 'Observation'], ['Classical control theory'], ['Quality control', 'Measurement', 'Tests', 'Metrology'], ['Classical control theory'], [], []]

data_input_text : Veterans Memorial Parkway (Evansville)
lbl2data_input_text : ['Indiana']
cat2data_input_text : ['Parkways in the United States', 'Transportation in Evansville, Indiana', 'Transportation in Vanderburgh County, Indiana', 'Roads in Indiana']
cat2lbl2data_input_text : [['Articles containing video clips', 'States and territories established in 1816', 'States of the United States', 'Midwestern United States', 'Contiguous United States', 'Indiana', '1816 establishments in the United States', 'U.S. states with multiple time zones']]

data_input_text : Manchester Boddy
lbl2data_input_text : ['Charles E. Downs', 'C.H. Garrigues', 'Charles Harris Garrigues']
cat2data_input_text : ['1891 births', '20th-century American businesspeople', '1967 deaths', 'California Democrats', 'American anti-communists', 'California Republicans', 'Businesspeople from Los Angeles', 'American newspaper publishers (people)', 'People from La Cañada Flintridge, California', 'People from La CaÃ±ada Flintridge, California']
cat2lbl2data_input_text : [['1898 births', '1967 deaths', 'California Republicans', '20th-century American politicians', '20th-century California politicians', 'Los Angeles City Council members'], [], ['20th-century American male writers', '20th-century American non-fiction writers', 'American male journalists', '20th-century American journalists', '1902 births', '1974 deaths', 'People from Brentwood, Los Angeles', 'The San Diego Union-Tribune people', 'People from WaKeeney, Kansas', 'Writers from Kansas']]

data_input_text : Lafayette B. Mendel House
lbl2data_input_text : ['National Register of Historic Places listings in New Haven, Connecticut', 'List of National Historic Landmarks in Connecticut']
cat2data_input_text : ['Houses on the National Register of Historic Places in Connecticut', 'Houses completed in 1858', 'National Register of Historic Places in New Haven, Connecticut', 'National Historic Landmarks in Connecticut', 'Houses in New Haven, Connecticut']
cat2lbl2data_input_text : [['National Register of Historic Places in New Haven, Connecticut', 'History of New Haven, Connecticut', 'Lists of National Register of Historic Places in Connecticut by populated place', 'Lists of National Register of Historic Places in Connecticut by city'], ['Lists of National Historic Landmarks by state', 'Connecticut-related lists', 'National Historic Landmarks in Connecticut', 'Lists of National Register of Historic Places in Connecticut']]

data_input_text : Ferriday Commercial Historic District
lbl2data_input_text : ['National Register of Historic Places listings in Concordia Parish, Louisiana']
cat2data_input_text : ['National Register of Historic Places in Concordia Parish, Louisiana', 'Italianate architecture in Louisiana', 'Historic districts on the National Register of Historic Places in Louisiana', 'Ferriday, Louisiana', 'Concordia Parish, Louisiana']
cat2lbl2data_input_text : [['Lists of National Register of Historic Places in Louisiana by parish', 'National Register of Historic Places in Concordia Parish, Louisiana']]

data_input_text : 1408 (film)
lbl2data_input_text : ['List of ghost films', 'List of adaptations of works by Stephen King', 'Silent Hill 4: The Room', 'Cell (film)', 'Cell']
cat2data_input_text : ['Films about writers', '2000s American films', '2000s English-language films', 'Films shot in Los Angeles', '2007 films', 'English-language horror thriller films', 'Metro-Goldwyn-Mayer films', 'American supernatural horror films', 'Films based on American short stories', 'American ghost films', 'American horror thriller films', 'Films shot in New York City', 'Films shot at Pinewood Studios', 'Films shot at Elstree Film Studios', 'Films set in hotels', '2007 horror films', 'Films based on short fiction', 'Films scored by Gabriel Yared', 'Films set in Manhattan', '2000s ghost films', 'Films shot in London', '2000s horror thriller films', 'The Weinstein Company films', 'Films about child death', 'Dimension Films films', 'American psychological horror films', '2000s psychological horror films', 'Films based on works by Stephen King', 'Films directed by Mikael Håfström', 'Fiction about haunted houses', 'Films with screenplays by Scott Alexander and Larry Karaszewski', 'Di Bonaventura Pictures films', 'Films produced by Lorenzo di Bonaventura', 'Films shot at Elstree Studios', 'American films', 'Films directed by Mikael HÃ¥fstrÃ¶m', 'Screenplays by Scott Alexander and Larry Karaszewski']
cat2lbl2data_input_text : [['Lists of films by common content', 'Fictional ghosts', 'Lists of films by topic', 'Lists of horror films', 'Television shows about ghosts', 'Ghost films'], ['Lists of television series based on works', 'Lists of films based on works', 'Adaptations of works by Stephen King'], ['Video games developed in Japan', 'Windows games', '2004 video games', 'Single-player video games', 'Video games about ghosts', 'Video games set in the United States', 'Xbox games', 'Psychological horror games', 'PlayStation 2 games', 'Konami games', '2000s horror video games', 'Video games scored by Akira Yamaoka', 'Survival horror video games', 'Silent Hill games'], ['2010s English-language films', '2010s American films', 'English-language science fiction horror films', 'American science fiction horror films', 'English-language thriller films', '2016 films', 'American science fiction thriller films', 'American horror television films', 'Films based on science fiction novels', 'Films shot in Atlanta', 'Films based on American horror novels', 'Films with screenplays by Stephen King', '2016 horror films', '2016 thriller films', '2010s science fiction horror films', 'Films scored by Marcelo Zarvos', 'Films based on works by Stephen King', 'Films directed by Tod Williams', 'Films about mobile phones', 'Saban Films films'], []]

### `new-new-new`

In [ ]:
o = show_func(new_dir)

                               # Entries  # Features  \
Split Dataset
Train Main                       1183189     1205595
      Query Category Metadata    1183189     1155247
      Label Category Metadata    1205595     1155247
Test  Main                        340278     1205595
      Query Category Metadata     340278     1155247
      Label Category Metadata    1205595     1155247

                               Avg. Entries per feature  \
Split Dataset
Train Main                                         2.57
      Query Category Metadata                      5.21
      Label Category Metadata                      3.75
Test  Main                                         0.82
      Query Category Metadata                      1.49
      Label Category Metadata                      3.75

                               Avg. Feature per entry  \
Split Dataset
Train Main                                       2.62
      Query Category Metadata                    5.09
      Label Category Metadata                    3.60
Test  Main                                       2.90
      Query Category Metadata                    5.06
      Label Category Metadata                    3.60

                               Max. Entries per feature  \
Split Dataset
Train Main                                         4747
      Query Category Metadata                     65056
      Label Category Metadata                     25831
Test  Main                                         1075
      Query Category Metadata                     17104
      Label Category Metadata                     25831

                               Max. Feature per entry  \
Split Dataset
Train Main                                        987
      Query Category Metadata                     245
      Label Category Metadata                     247
Test  Main                                        150
      Query Category Metadata                     247
      Label Category Metadata                     247

                               # Features without entry  \
Split Dataset
Train Main                                            0
      Query Category Metadata                    159691
      Label Category Metadata                    280544
Test  Main                                       758109
      Query Category Metadata                    625513
      Label Category Metadata                    280544

                               # Entries without feature
Split Dataset
Train Main                                             0
      Query Category Metadata                     102390
      Label Category Metadata                     420595
Test  Main                                             0
      Query Category Metadata                      24033
      Label Category Metadata                     420595

data_input_text : Adolf Fleischmann
lbl2data_input_text : ['List of German painters']
cat2data_input_text : ['1968 deaths', 'State Academy of Fine Arts Stuttgart alumni', 'German Army personnel of World War I', 'German abstract painters', 'Artists from the Kingdom of Württemberg', '1892 births', 'People from Esslingen am Neckar']
cat2lbl2data_input_text : [['Lists of German people by occupation', 'German painters', 'Lists of painters by nationality']]

data_input_text : Fell (novel)
lbl2data_input_text : ['Fire Bringer', 'The Sight (Clement-Davies novel)']
cat2data_input_text : ['Novels about wolves', 'American fantasy novels', '2007 American novels', 'Amulet Books books']
cat2lbl2data_input_text : [['British fantasy novels', 'Novels set in Scotland', 'Novels about animals', 'Fiction about precognition', '1999 British novels', 'Novels set in the 13th century', 'Macmillan Publishers books', '1999 fantasy novels', 'British young adult novels'], ['2002 fantasy novels', 'Novels about wolves', '2002 British novels', 'Macmillan Publishers books']]

data_input_text : Fairchild Dornier 428JET
lbl2data_input_text : ['Embraer ERJ 140', 'Fairchild Dornier 328JET']
cat2data_input_text : ['Fairchild aircraft', 'Abandoned civil aircraft projects', 'T-tail aircraft', 'Dornier aircraft', 'High-wing aircraft', 'Twinjets', 'Aircraft with retractable tricycle landing gear']
cat2lbl2data_input_text : [[], ['Fairchild aircraft', 'T-tail aircraft', 'Dornier aircraft', '1990s international airliners', 'Aircraft first flown in 1998', 'Twinjets', 'Aircraft with retractable tricycle landing gear']]

data_input_text : MBASE
lbl2data_input_text : ['Model-driven engineering', 'Model-driven architecture', 'Object Management Group']
cat2data_input_text : ['Software development process']
cat2lbl2data_input_text : [['Unified Modeling Language', 'Systems engineering'], ['Unified Modeling Language', 'Systems engineering', 'Software architecture'], ['Unified Modeling Language', 'Standards organizations in the United States']]

data_input_text : Donor conceived person
lbl2data_input_text : ['Dibling', 'Sperm donation', 'Egg donor', 'Accidental incest']
cat2data_input_text : ['Family law', 'Artificial insemination', 'Fertility medicine', 'Human reproduction', 'Sperm donation']
cat2lbl2data_input_text : [['Fertility medicine', 'Sibling', 'Sperm donation', 'Kinship and descent'], ['Giving', 'Sperm donation', 'Semen'], [], ['Accidents', 'Sperm donation', 'Incest']]

data_input_text : Cumbrian Newspapers Group Ltd v Cumberland & Westmoreland Herald Ltd
lbl2data_input_text : ['UK company law']
cat2data_input_text : ['1986 in United Kingdom case law', 'High Court of Justice cases', 'United Kingdom company case law']
cat2lbl2data_input_text : [[]]

data_input_text : Toowoomba Grammar School
lbl2data_input_text : ['List of boarding schools', 'List of schools in Queensland']
cat2data_input_text : ['East Toowoomba', 'High schools in Queensland', 'Private schools in Queensland', 'Boarding schools in Queensland', "Boys' schools in Queensland", 'Junior School Heads Association of Australia Member Schools', 'Willoughby Powell buildings', 'Great Public Schools Association of Queensland', 'Schools in Toowoomba', 'Grammar schools in Australia', '1875 establishments in Australia', 'Educational institutions established in 1875']
cat2lbl2data_input_text : [['Lists of boarding schools'], []]

data_input_text : Saint-Cirgues-sur-Couze
lbl2data_input_text : ['Communes of the Puy-de-Dôme department']
cat2data_input_text : ['Former communes of Puy-de-Dôme']
cat2lbl2data_input_text : [['Lists of communes of France', 'Communes of Puy-de-Dôme']]

data_input_text : Kaligandaki Corridor
lbl2data_input_text : ['National Pride Projects', 'List of roads in Nepal']
cat2data_input_text : ['Highways in Nepal']
cat2lbl2data_input_text : [['Proposed infrastructure', 'National Pride Projects', 'Infrastructure in Nepal', 'Nepal-related lists'], ['Nepal transport-related lists', 'Roads in Nepal', 'Lists of buildings and structures in Nepal', 'Lists of roads by country']]

data_input_text : Virt Records
lbl2data_input_text : ['List of record labels']
cat2data_input_text : ['Pop record labels', 'American independent record labels']
cat2lbl2data_input_text : [[]]

### `new-combined-new`

In [ ]:
o = updated_show_func(x_prefix='new', y_prefix='combined', z_prefix='new')

                               # Entries  # Features  \
Split Dataset
Train Main                       1279129     1262951
      Query Category Metadata    1279129     1158817
      Label Category Metadata    1262951     1158817
Test  Main                        428679     1262951
      Query Category Metadata     428679     1158817
      Label Category Metadata    1262951     1158817

                               Avg. Entries per feature  \
Split Dataset
Train Main                                         2.86
      Query Category Metadata                      5.41
      Label Category Metadata                      3.90
Test  Main                                         0.94
      Query Category Metadata                      1.74
      Label Category Metadata                      3.90

                               Avg. Feature per entry  \
Split Dataset
Train Main                                       2.83
      Query Category Metadata                    4.90
      Label Category Metadata                    3.58
Test  Main                                       2.76
      Query Category Metadata                    4.70
      Label Category Metadata                    3.58

                               Max. Entries per feature  \
Split Dataset
Train Main                                         5353
      Query Category Metadata                     68304
      Label Category Metadata                     26480
Test  Main                                         1075
      Query Category Metadata                     20107
      Label Category Metadata                     26480

                               Max. Feature per entry  \
Split Dataset
Train Main                                        987
      Query Category Metadata                     245
      Label Category Metadata                     247
Test  Main                                        151
      Query Category Metadata                     247
      Label Category Metadata                     247

                               # Features without entry  \
Split Dataset
Train Main                                          262
      Query Category Metadata                    148381
      Label Category Metadata                    270838
Test  Main                                       732675
      Query Category Metadata                    573303
      Label Category Metadata                    270838

                               # Entries without feature
Split Dataset
Train Main                                          6157
      Query Category Metadata                     160364
      Label Category Metadata                     444111
Test  Main                                         63684
      Query Category Metadata                      56352
      Label Category Metadata                     444111

data_input_text : Certificate of Formula Compliance
lbl2data_input_text : ['Certificate of origin', 'Certificate of Origin']
cat2data_input_text : ['Cosmetic industry', 'International trade documents']
cat2lbl2data_input_text : [['Export', 'International trade documents'], []]

data_input_text : 2017 Sunwolves season
lbl2data_input_text : ['Sunwolves', '2017 Super Rugby season']
cat2data_input_text : ['2016–17 in Japanese rugby union', 'Sunwolves seasons', '2017–18 in Japanese rugby union', '2017 Super Rugby season by team']
cat2lbl2data_input_text : [['2020 disestablishments in Japan', 'Sunwolves', 'Rugby clubs established in 2015', '2015 establishments in Japan', 'Rugby union in Singapore', 'Rugby union clubs disestablished in 2020', 'Super Rugby teams', 'Rugby union teams in Tokyo'], ['2017 in Argentine rugby union', '2016–17 in Japanese rugby union', '2017 in Australian rugby union', '2017 rugby union tournaments for clubs', 'Super Rugby seasons', '2017 Super Rugby season', '2017 in New Zealand rugby union', '2017 in South African rugby union', '2017–18 in Japanese rugby union']]

data_input_text : Hadza people
lbl2data_input_text : ['Twa peoples', 'Mbuti people', 'Aka people', 'Baka people (Cameroon and Gabon)', 'Bongo people (Gabon)', 'Bushmen', '!Kung people', 'Twa']
cat2data_input_text : ['Hunter-gatherers of Africa', 'Indigenous peoples of East Africa', 'Ethnic groups in Tanzania']
cat2lbl2data_input_text : [[], ['Ethnic groups in the Democratic Republic of the Congo', 'African Pygmies'], ['Modern nomads', 'African Pygmies', 'Ethnic groups in the Democratic Republic of the Congo', 'Ethnic groups in the Central African Republic'], ['Ethnic groups in Cameroon', 'Ethnic groups in the Republic of the Congo', 'Ethnic groups in the Central African Republic', 'African Pygmies', 'Ethnic groups in Gabon', 'Modern nomads'], ['African Pygmies'], [], [], ['Ethnic groups in Zambia', 'Ethnic groups in Botswana', 'Ethnic groups in the Democratic Republic of the Congo', 'African Pygmies', 'Ethnic groups in Namibia', 'Ethnic groups in Angola']]

data_input_text : The Lost City (2005 film)
lbl2data_input_text : ['List of American films of 2005']
cat2data_input_text : ['Films about Jewish-American organized crime', 'Cultural depictions of Meyer Lansky', '2005 drama films', '2000s political drama films', 'Films set in Havana', 'Magnolia Pictures films', 'American political drama films', 'Films about the American Mafia', '2000s American films', 'Lionsgate films', 'Films shot in the Dominican Republic', '2005 films', 'Films set in 1958', 'Cultural depictions of Che Guevara']
cat2lbl2data_input_text : [['Lists of American films by year', '2005 in American cinema', 'Lists of 2005 films by country']]

data_input_text : Testability
lbl2data_input_text : ['Scientific method', 'Test method', 'Testability', 'Observability', 'Controllability', 'Confirmability', 'Contingency']
cat2data_input_text : ['Empiricism', 'Logic', 'Observation', 'Scientific method', 'Philosophy of science']
cat2lbl2data_input_text : [['Scientific method', 'Empiricism', 'Philosophy of science', 'Scientific Revolution'], ['Measurement', 'Tests', 'Metrology', 'Quality control'], ['Empiricism', 'Logic', 'Observation', 'Scientific method', 'Philosophy of science'], ['Classical control theory'], ['Classical control theory'], [], []]

data_input_text : Veterans Memorial Parkway (Evansville)
lbl2data_input_text : ['Numbered highways in the United States', 'Indiana']
cat2data_input_text : []
cat2lbl2data_input_text : [['Road signs in the United States', 'United States state insignia', 'State highways in the United States', 'Highways in the United States'], ['States and territories established in 1816', 'States of the United States', 'Midwestern United States', 'Indiana', 'Articles containing video clips', '1816 establishments in the United States', 'Contiguous United States']]

data_input_text : Manchester Boddy
lbl2data_input_text : ['Charles E. Downs', 'C.H. Garrigues', 'Charles Harris Garrigues']
cat2data_input_text : ['People from La Cañada Flintridge, California', '1891 births', 'American anti-communists', '20th-century American businesspeople', 'American newspaper publishers (people)', 'California Republicans', '1967 deaths', 'Businesspeople from Los Angeles', 'California Democrats']
cat2lbl2data_input_text : [['Los Angeles City Council members', '1898 births', 'California Republicans', '1967 deaths', '20th-century California politicians'], [], ['The San Diego Union-Tribune people', 'American male journalists', '20th-century American male writers', 'People from WaKeeney, Kansas', '1902 births', '1974 deaths', 'Writers from Kansas', 'People from Brentwood, Los Angeles', '20th-century American journalists', '20th-century American non-fiction writers']]

data_input_text : Lafayette B. Mendel House
lbl2data_input_text : ['National Register of Historic Places listings in New Haven, Connecticut', 'List of National Historic Landmarks in Connecticut']
cat2data_input_text : ['National Register of Historic Places in New Haven, Connecticut', 'Houses in New Haven, Connecticut', 'National Historic Landmarks in Connecticut', 'Houses on the National Register of Historic Places in Connecticut', 'Houses completed in 1858']
cat2lbl2data_input_text : [['History of New Haven, Connecticut', 'National Register of Historic Places in New Haven, Connecticut', 'Lists of National Register of Historic Places in Connecticut by populated place'], ['Lists of National Register of Historic Places in Connecticut', 'Lists of National Historic Landmarks by state', 'National Historic Landmarks in Connecticut']]

data_input_text : Ferriday Commercial Historic District
lbl2data_input_text : ['National Register of Historic Places listings in Concordia Parish, Louisiana']
cat2data_input_text : ['National Register of Historic Places in Concordia Parish, Louisiana', 'Italianate architecture in Louisiana', 'Historic districts on the National Register of Historic Places in Louisiana', 'Ferriday, Louisiana']
cat2lbl2data_input_text : [['National Register of Historic Places in Concordia Parish, Louisiana', 'Lists of National Register of Historic Places in Louisiana by parish']]

data_input_text : 1408 (film)
lbl2data_input_text : ['List of ghost films', 'List of adaptations of works by Stephen King', 'Silent Hill 4: The Room', 'Cell (film)', 'Cell']
cat2data_input_text : ['Films with screenplays by Scott Alexander and Larry Karaszewski', 'Di Bonaventura Pictures films', 'Films shot at Pinewood Studios', 'American supernatural horror films', '2000s horror thriller films', '2007 horror films', 'Films set in Manhattan', 'Films set in hotels', 'English-language horror thriller films', 'Films about writers', 'Films based on works by Stephen King', 'The Weinstein Company films', 'Films shot in London', 'Films directed by Mikael Håfström', 'American ghost films', 'Films about child death', 'Films produced by Lorenzo di Bonaventura', '2000s ghost films', '2000s psychological horror films', 'Films shot at Elstree Film Studios', 'Metro-Goldwyn-Mayer films', 'Films scored by Gabriel Yared', 'Fiction about haunted houses', '2000s American films', 'American horror thriller films', 'Films shot in New York City', 'Films based on American short stories', '2007 films', '2000s English-language films', 'Films shot in Los Angeles', 'American psychological horror films', 'Dimension Films films']
cat2lbl2data_input_text : [['Lists of horror films', 'Lists of films by topic', 'Television shows about ghosts', 'Ghost films', 'Lists of films by common content', 'Fictional ghosts'], ['Adaptations of works by Stephen King', 'Lists of films based on works', 'Lists of television series based on works'], ['Video games developed in Japan', '2004 video games', 'Single-player video games', 'Video games set in the United States', 'Survival horror video games', 'Video games about ghosts', 'Windows games', '2000s horror video games', 'Xbox games', 'Konami games', 'PlayStation 2 games', 'Video games scored by Akira Yamaoka', 'Psychological horror games', 'Silent Hill games'], ['Films about mobile phones', 'Saban Films films', 'English-language science fiction horror films', 'American horror television films', 'Films based on science fiction novels', '2010s science fiction horror films', 'Films directed by Tod Williams', '2016 thriller films', 'Films based on works by Stephen King', 'American science fiction thriller films', 'Films scored by Marcelo Zarvos', '2016 horror films', '2010s American films', 'Films shot in Atlanta', 'American science fiction horror films', '2016 films', 'Films based on American horror novels', '2010s English-language films', 'Films with screenplays by Stephen King', 'English-language thriller films'], []]

### `new-new-combined`

In [ ]:
o = updated_show_func(x_prefix='new', y_prefix='new', z_prefix='combined')

                               # Entries  # Features  \
Split Dataset
Train Main                       1279129     1205595
      Query Category Metadata    1279129     1246828
      Label Category Metadata    1205595     1246828
Test  Main                        428679     1205595
      Query Category Metadata     428679     1246828
      Label Category Metadata    1205595     1246828

                               Avg. Entries per feature  \
Split Dataset
Train Main                                         2.57
      Query Category Metadata                      5.82
      Label Category Metadata                      3.64
Test  Main                                         0.82
      Query Category Metadata                      1.80
      Label Category Metadata                      3.64

                               Avg. Feature per entry  \
Split Dataset
Train Main                                       2.42
      Query Category Metadata                    5.67
      Label Category Metadata                    3.77
Test  Main                                       2.30
      Query Category Metadata                    5.24
      Label Category Metadata                    3.77

                               Max. Entries per feature  \
Split Dataset
Train Main                                         4747
      Query Category Metadata                     76346
      Label Category Metadata                     26116
Test  Main                                         1075
      Query Category Metadata                     21406
      Label Category Metadata                     26116

                               Max. Feature per entry  \
Split Dataset
Train Main                                        987
      Query Category Metadata                     287
      Label Category Metadata                     287
Test  Main                                        150
      Query Category Metadata                     256
      Label Category Metadata                     287

                               # Features without entry  \
Split Dataset
Train Main                                            0
      Query Category Metadata                    147508
      Label Category Metadata                    337245
Test  Main                                       758109
      Query Category Metadata                    616907
      Label Category Metadata                    337245

                               # Entries without feature
Split Dataset
Train Main                                         95940
      Query Category Metadata                     102746
      Label Category Metadata                     420253
Test  Main                                         88401
      Query Category Metadata                      44992
      Label Category Metadata                     420253

data_input_text : Certificate of Formula Compliance
lbl2data_input_text : ['Certificate of Origin']
cat2data_input_text : ['Cosmetic industry', 'International trade documents']
cat2lbl2data_input_text : [[]]

data_input_text : 2017 Sunwolves season
lbl2data_input_text : ['Sunwolves', '2017 Super Rugby season']
cat2data_input_text : ['2016–17 in Japanese rugby union', 'Sunwolves seasons', '2017–18 in Japanese rugby union', '2017 Super Rugby season by team', '2016â\x80\x9317 in Japanese rugby union', '2017â\x80\x9318 in Japanese rugby union']
cat2lbl2data_input_text : [['2020 disestablishments in Japan', 'Sunwolves', 'Rugby clubs established in 2015', '2015 establishments in Japan', 'Rugby union in Singapore', 'Rugby union clubs disestablished in 2020', 'Super Rugby teams', 'Rugby union teams in Tokyo', 'Sports teams in Tokyo'], ['2017 Super Rugby season', '2016–17 in Japanese rugby union', '2017 in South African rugby union', '2017 rugby union tournaments for clubs', '2017 in New Zealand rugby union', '2017–18 in Japanese rugby union', '2017 in Argentine rugby union', '2017 in Australian rugby union', 'Super Rugby seasons', '2016â\x80\x9317 in Japanese rugby union', '2017â\x80\x9318 in Japanese rugby union']]

data_input_text : Hadza people
lbl2data_input_text : ['Mbuti people', 'Baka people (Cameroon and Gabon)', 'Bongo people (Gabon)', 'Bushmen', '!Kung people', 'Aka people', 'Twa peoples']
cat2data_input_text : ['Indigenous peoples of East Africa', 'Ethnic groups in Tanzania', 'Hunter-gatherers of Africa']
cat2lbl2data_input_text : [['Ethnic groups in the Democratic Republic of the Congo', 'African Pygmies'], ['Modern nomads', 'Ethnic groups in Cameroon', 'Ethnic groups in the Republic of the Congo', 'Ethnic groups in the Central African Republic', 'African Pygmies', 'Ethnic groups in Gabon'], ['African Pygmies'], [], [], ['Modern nomads', 'Ethnic groups in the Democratic Republic of the Congo', 'Ethnic groups in the Central African Republic', 'African Pygmies', 'Modern_nomads'], []]

data_input_text : The Lost City (2005 film)
lbl2data_input_text : ['List of American films of 2005']
cat2data_input_text : ['2005 films', '2000s American films', 'American political drama films', 'Films set in 1958', 'Films about the American Mafia', '2005 drama films', 'Lionsgate films', 'Magnolia Pictures films', 'Films set in Havana', 'Films shot in the Dominican Republic', 'Films set in Cuba', '2000s political drama films', 'Mafia films', 'Films about Jewish-American organized crime', '2000s drama films', 'Cultural depictions of Che Guevara', 'Cultural depictions of Meyer Lansky', 'American films', 'Lions Gate Entertainment films']
cat2lbl2data_input_text : [['Lists of American films by year', 'Lists of 2005 films by country', '2005 in American cinema', 'Lists of 2005 films by country or language']]

data_input_text : Testability
lbl2data_input_text : ['Confirmability', 'Test method', 'Controllability', 'Observability', 'Scientific method']
cat2data_input_text : ['Philosophy of science', 'Empiricism', 'Logic', 'Scientific method', 'Observation']
cat2lbl2data_input_text : [[], ['Quality control', 'Measurement', 'Tests', 'Metrology'], ['Classical control theory'], ['Classical control theory'], ['Philosophy of science', 'Empiricism', 'Scientific method', 'Scientific Revolution']]

data_input_text : Veterans Memorial Parkway (Evansville)
lbl2data_input_text : []
cat2data_input_text : ['Parkways in the United States', 'Transportation in Evansville, Indiana', 'Transportation in Vanderburgh County, Indiana', 'Roads in Indiana']
cat2lbl2data_input_text : []

data_input_text : Manchester Boddy
lbl2data_input_text : ['Charles E. Downs', 'C.H. Garrigues']
cat2data_input_text : ['1891 births', '20th-century American businesspeople', '1967 deaths', 'California Democrats', 'American anti-communists', 'California Republicans', 'American newspaper publishers (people)', 'Businesspeople from Los Angeles', 'People from La Cañada Flintridge, California', 'People from La CaÃ±ada Flintridge, California']
cat2lbl2data_input_text : [['1898 births', '1967 deaths', 'California Republicans', '20th-century California politicians', 'Los Angeles City Council members', '20th-century American politicians'], []]

data_input_text : Lafayette B. Mendel House
lbl2data_input_text : ['List of National Historic Landmarks in Connecticut', 'National Register of Historic Places listings in New Haven, Connecticut']
cat2data_input_text : ['Houses on the National Register of Historic Places in Connecticut', 'Houses completed in 1858', 'National Register of Historic Places in New Haven, Connecticut', 'National Historic Landmarks in Connecticut', 'Houses in New Haven, Connecticut']
cat2lbl2data_input_text : [['Lists of National Historic Landmarks by state', 'Connecticut-related lists', 'National Historic Landmarks in Connecticut', 'Lists of National Register of Historic Places in Connecticut'], ['National Register of Historic Places in New Haven, Connecticut', 'Lists of National Register of Historic Places in Connecticut by populated place', 'History of New Haven, Connecticut', 'Lists of National Register of Historic Places in Connecticut by city']]

data_input_text : Ferriday Commercial Historic District
lbl2data_input_text : ['National Register of Historic Places listings in Concordia Parish, Louisiana']
cat2data_input_text : ['Historic districts on the National Register of Historic Places in Louisiana', 'Italianate architecture in Louisiana', 'National Register of Historic Places in Concordia Parish, Louisiana', 'Concordia Parish, Louisiana', 'Ferriday, Louisiana']
cat2lbl2data_input_text : [['Lists of National Register of Historic Places in Louisiana by parish', 'National Register of Historic Places in Concordia Parish, Louisiana']]

data_input_text : 1408 (film)
lbl2data_input_text : ['Silent Hill 4: The Room', 'List of ghost films', 'List of adaptations of works by Stephen King', 'Cell (film)']
cat2data_input_text : ['Films shot in Los Angeles', 'American supernatural horror films', 'Films shot in London', 'Films shot in New York City', '2000s English-language films', 'American horror thriller films', '2000s horror thriller films', '2007 horror films', 'English-language horror thriller films', 'Films based on works by Stephen King', 'The Weinstein Company films', 'Metro-Goldwyn-Mayer films', '2000s American films', '2007 films', 'Dimension Films films', 'Films based on American short stories', 'American ghost films', 'Films set in hotels', 'Films based on short fiction', 'Films shot at Pinewood Studios', 'Films set in Manhattan', 'Films about writers', 'Films about child death', 'Films scored by Gabriel Yared', 'American psychological horror films', '2000s psychological horror films', '2000s ghost films', 'Films shot at Elstree Film Studios', 'Di Bonaventura Pictures films', 'Films produced by Lorenzo di Bonaventura', 'Fiction about haunted houses', 'Films directed by Mikael Håfström', 'Films shot at Elstree Studios', 'Films with screenplays by Scott Alexander and Larry Karaszewski', 'American films', 'Films directed by Mikael HÃ¥fstrÃ¶m', 'Screenplays by Scott Alexander and Larry Karaszewski']
cat2lbl2data_input_text : [['Windows games', 'Video games set in the United States', 'Video games developed in Japan', 'Single-player video games', '2004 video games', 'Video games about ghosts', 'Psychological horror games', 'PlayStation 2 games', 'Konami games', 'Xbox games', 'Video games scored by Akira Yamaoka', '2000s horror video games', 'Survival horror video games', 'Silent Hill games'], ['Fictional ghosts', 'Lists of films by common content', 'Lists of films by topic', 'Television shows about ghosts', 'Lists of horror films', 'Ghost films'], ['Lists of films based on works', 'Lists of television series based on works', 'Adaptations of works by Stephen King'], ['2016 films', '2010s English-language films', '2010s American films', 'Films based on American horror novels', 'English-language thriller films', 'English-language science fiction horror films', 'American science fiction horror films', 'Films based on works by Stephen King', 'American science fiction thriller films', 'American horror television films', 'Films based on science fiction novels', 'Films about mobile phones', '2016 horror films', 'Films shot in Atlanta', '2016 thriller films', 'Saban Films films', '2010s science fiction horror films', 'Films scored by Marcelo Zarvos', 'Films with screenplays by Stephen King', 'Films directed by Tod Williams']]

### `new-combined-combined`

In [ ]:
o = updated_show_func(x_prefix='new', y_prefix='combined', z_prefix='combined')

                               # Entries  # Features  \
Split Dataset
Train Main                       1279129     1262951
      Query Category Metadata    1279129     1249083
      Label Category Metadata    1262951     1249083
Test  Main                        428679     1262951
      Query Category Metadata     428679     1249083
      Label Category Metadata    1262951     1249083

                               Avg. Entries per feature  \
Split Dataset
Train Main                                         2.86
      Query Category Metadata                      5.81
      Label Category Metadata                      3.81
Test  Main                                         0.94
      Query Category Metadata                      1.80
      Label Category Metadata                      3.81

                               Avg. Feature per entry  \
Split Dataset
Train Main                                       2.83
      Query Category Metadata                    5.67
      Label Category Metadata                    3.77
Test  Main                                       2.76
      Query Category Metadata                    5.25
      Label Category Metadata                    3.77

                               Max. Entries per feature  \
Split Dataset
Train Main                                         5353
      Query Category Metadata                     76346
      Label Category Metadata                     26896
Test  Main                                         1075
      Query Category Metadata                     21406
      Label Category Metadata                     26896

                               Max. Feature per entry  \
Split Dataset
Train Main                                        987
      Query Category Metadata                     287
      Label Category Metadata                     287
Test  Main                                        151
      Query Category Metadata                     256
      Label Category Metadata                     287

                               # Features without entry  \
Split Dataset
Train Main                                          262
      Query Category Metadata                    149761
      Label Category Metadata                    322177
Test  Main                                       732675
      Query Category Metadata                    617822
      Label Category Metadata                    322177

                               # Entries without feature
Split Dataset
Train Main                                          6157
      Query Category Metadata                     102746
      Label Category Metadata                     440946
Test  Main                                         63684
      Query Category Metadata                      44972
      Label Category Metadata                     440946

data_input_text : Certificate of Formula Compliance
lbl2data_input_text : ['Certificate of origin', 'Certificate of Origin']
cat2data_input_text : ['Cosmetic industry', 'International trade documents']
cat2lbl2data_input_text : [['Export', 'International trade documents'], []]

data_input_text : 2017 Sunwolves season
lbl2data_input_text : ['Sunwolves', '2017 Super Rugby season']
cat2data_input_text : ['2016–17 in Japanese rugby union', 'Sunwolves seasons', '2017–18 in Japanese rugby union', '2017 Super Rugby season by team', '2016â\x80\x9317 in Japanese rugby union', '2017â\x80\x9318 in Japanese rugby union']
cat2lbl2data_input_text : [['2020 disestablishments in Japan', 'Sunwolves', 'Rugby clubs established in 2015', '2015 establishments in Japan', 'Rugby union in Singapore', 'Rugby union clubs disestablished in 2020', 'Super Rugby teams', 'Rugby union teams in Tokyo', 'Sports teams in Tokyo'], ['2017 Super Rugby season', '2016–17 in Japanese rugby union', '2017 in South African rugby union', '2017 rugby union tournaments for clubs', '2017 in New Zealand rugby union', '2017–18 in Japanese rugby union', '2017 in Argentine rugby union', '2017 in Australian rugby union', 'Super Rugby seasons', '2016â\x80\x9317 in Japanese rugby union', '2017â\x80\x9318 in Japanese rugby union']]

data_input_text : Hadza people
lbl2data_input_text : ['Twa peoples', 'Mbuti people', 'Aka people', 'Baka people (Cameroon and Gabon)', 'Bongo people (Gabon)', 'Bushmen', '!Kung people', 'Twa']
cat2data_input_text : ['Indigenous peoples of East Africa', 'Ethnic groups in Tanzania', 'Hunter-gatherers of Africa']
cat2lbl2data_input_text : [[], ['Ethnic groups in the Democratic Republic of the Congo', 'African Pygmies'], ['Modern nomads', 'Ethnic groups in the Democratic Republic of the Congo', 'Ethnic groups in the Central African Republic', 'African Pygmies', 'Modern_nomads'], ['Modern nomads', 'Ethnic groups in Cameroon', 'Ethnic groups in the Republic of the Congo', 'Ethnic groups in the Central African Republic', 'African Pygmies', 'Ethnic groups in Gabon'], ['African Pygmies'], [], [], ['Ethnic groups in the Democratic Republic of the Congo', 'Ethnic groups in Namibia', 'Ethnic groups in Zambia', 'Ethnic groups in Angola', 'African Pygmies', 'Ethnic groups in Botswana']]

data_input_text : The Lost City (2005 film)
lbl2data_input_text : ['List of American films of 2005']
cat2data_input_text : ['2005 films', '2000s American films', 'American political drama films', 'Films set in 1958', 'Films about the American Mafia', '2005 drama films', 'Lionsgate films', 'Magnolia Pictures films', 'Films set in Havana', 'Films shot in the Dominican Republic', 'Films set in Cuba', '2000s political drama films', 'Mafia films', 'Films about Jewish-American organized crime', '2000s drama films', 'Cultural depictions of Che Guevara', 'Cultural depictions of Meyer Lansky', 'American films', 'Lions Gate Entertainment films']
cat2lbl2data_input_text : [['Lists of American films by year', 'Lists of 2005 films by country', '2005 in American cinema', 'Lists of 2005 films by country or language']]

data_input_text : Testability
lbl2data_input_text : ['Scientific method', 'Test method', 'Testability', 'Observability', 'Controllability', 'Confirmability', 'Contingency']
cat2data_input_text : ['Philosophy of science', 'Empiricism', 'Logic', 'Scientific method', 'Observation']
cat2lbl2data_input_text : [['Philosophy of science', 'Empiricism', 'Scientific method', 'Scientific Revolution'], ['Quality control', 'Measurement', 'Tests', 'Metrology'], ['Philosophy of science', 'Empiricism', 'Logic', 'Scientific method', 'Observation'], ['Classical control theory'], ['Classical control theory'], [], []]

data_input_text : Veterans Memorial Parkway (Evansville)
lbl2data_input_text : ['Numbered highways in the United States', 'Indiana']
cat2data_input_text : ['Parkways in the United States', 'Transportation in Evansville, Indiana', 'Transportation in Vanderburgh County, Indiana', 'Roads in Indiana']
cat2lbl2data_input_text : [['Road signs in the United States', 'Highways in the United States', 'United States state insignia', 'State highways in the United States'], ['Articles containing video clips', 'States and territories established in 1816', 'States of the United States', 'Midwestern United States', 'Contiguous United States', 'Indiana', '1816 establishments in the United States', 'U.S. states with multiple time zones']]

data_input_text : Manchester Boddy
lbl2data_input_text : ['Charles E. Downs', 'C.H. Garrigues', 'Charles Harris Garrigues']
cat2data_input_text : ['1891 births', '20th-century American businesspeople', '1967 deaths', 'California Democrats', 'American anti-communists', 'California Republicans', 'American newspaper publishers (people)', 'Businesspeople from Los Angeles', 'People from La Cañada Flintridge, California', 'People from La CaÃ±ada Flintridge, California']
cat2lbl2data_input_text : [['1898 births', '1967 deaths', 'California Republicans', '20th-century California politicians', 'Los Angeles City Council members', '20th-century American politicians'], [], ['20th-century American male writers', '1902 births', '20th-century American non-fiction writers', 'American male journalists', '20th-century American journalists', '1974 deaths', 'People from Brentwood, Los Angeles', 'Writers from Kansas', 'People from WaKeeney, Kansas', 'The San Diego Union-Tribune people']]

data_input_text : Lafayette B. Mendel House
lbl2data_input_text : ['National Register of Historic Places listings in New Haven, Connecticut', 'List of National Historic Landmarks in Connecticut']
cat2data_input_text : ['Houses on the National Register of Historic Places in Connecticut', 'Houses completed in 1858', 'National Register of Historic Places in New Haven, Connecticut', 'National Historic Landmarks in Connecticut', 'Houses in New Haven, Connecticut']
cat2lbl2data_input_text : [['National Register of Historic Places in New Haven, Connecticut', 'Lists of National Register of Historic Places in Connecticut by populated place', 'History of New Haven, Connecticut', 'Lists of National Register of Historic Places in Connecticut by city'], ['Lists of National Historic Landmarks by state', 'Connecticut-related lists', 'National Historic Landmarks in Connecticut', 'Lists of National Register of Historic Places in Connecticut']]

data_input_text : Ferriday Commercial Historic District
lbl2data_input_text : ['National Register of Historic Places listings in Concordia Parish, Louisiana']
cat2data_input_text : ['Historic districts on the National Register of Historic Places in Louisiana', 'Italianate architecture in Louisiana', 'National Register of Historic Places in Concordia Parish, Louisiana', 'Concordia Parish, Louisiana', 'Ferriday, Louisiana']
cat2lbl2data_input_text : [['Lists of National Register of Historic Places in Louisiana by parish', 'National Register of Historic Places in Concordia Parish, Louisiana']]

data_input_text : 1408 (film)
lbl2data_input_text : ['List of ghost films', 'List of adaptations of works by Stephen King', 'Silent Hill 4: The Room', 'Cell (film)', 'Cell']
cat2data_input_text : ['Films shot in Los Angeles', 'American supernatural horror films', 'Films shot in London', 'Films shot in New York City', '2000s English-language films', 'American horror thriller films', '2000s horror thriller films', '2007 horror films', 'English-language horror thriller films', 'Films based on works by Stephen King', 'The Weinstein Company films', 'Metro-Goldwyn-Mayer films', '2000s American films', '2007 films', 'Dimension Films films', 'Films based on American short stories', 'American ghost films', 'Films set in hotels', 'Films based on short fiction', 'Films shot at Pinewood Studios', 'Films set in Manhattan', 'Films about writers', 'Films about child death', 'Films scored by Gabriel Yared', 'American psychological horror films', '2000s psychological horror films', '2000s ghost films', 'Films shot at Elstree Film Studios', 'Di Bonaventura Pictures films', 'Films produced by Lorenzo di Bonaventura', 'Fiction about haunted houses', 'Films directed by Mikael Håfström', 'Films shot at Elstree Studios', 'Films with screenplays by Scott Alexander and Larry Karaszewski', 'American films', 'Films directed by Mikael HÃ¥fstrÃ¶m', 'Screenplays by Scott Alexander and Larry Karaszewski']
cat2lbl2data_input_text : [['Fictional ghosts', 'Lists of films by common content', 'Lists of films by topic', 'Television shows about ghosts', 'Lists of horror films', 'Ghost films'], ['Lists of films based on works', 'Lists of television series based on works', 'Adaptations of works by Stephen King'], ['Windows games', 'Video games set in the United States', 'Video games developed in Japan', 'Single-player video games', '2004 video games', 'Video games about ghosts', 'Psychological horror games', 'PlayStation 2 games', 'Konami games', 'Xbox games', 'Video games scored by Akira Yamaoka', '2000s horror video games', 'Survival horror video games', 'Silent Hill games'], ['2016 films', '2010s English-language films', '2010s American films', 'Films based on American horror novels', 'English-language thriller films', 'English-language science fiction horror films', 'American science fiction horror films', 'Films based on works by Stephen King', 'American science fiction thriller films', 'American horror television films', 'Films based on science fiction novels', 'Films about mobile phones', '2016 horror films', 'Films shot in Atlanta', '2016 thriller films', 'Saban Films films', '2010s science fiction horror films', 'Films scored by Marcelo Zarvos', 'Films with screenplays by Stephen King', 'Films directed by Tod Williams'], []]

## Comparision

In [ ]:
old_trn_dset, old_tst_dset = UpdatedDataset.load_datasets(save_dir, metadata_type, x_prefix='old', y_prefix='old', z_prefix='old')
new_trn_dset, new_tst_dset = UpdatedDataset.load_datasets(save_dir, metadata_type, x_prefix='old', y_prefix='new', z_prefix='new')

/home/scai/phd/aiz218323/.local/lib/python3.9/site-packages/xclib-0.97-py3.9-linux-x86_64.egg/xclib/data/data_utils.py:263: UserWarning: Header mis-match from inferred shape!
  warnings.warn("Header mis-match from inferred shape!")

# `LF-Amazon-131K`

In [ ]:
data_dir = '/home/scai/phd/aiz218323/scratch/datasets/benchmarks/LF-Amazon-131K/'

indices = np.random.permutation(294805)[:10]
show_func = partial(show_dataset, data_dir, idxs=indices)

## `Videos`

In [ ]:
show_func(metadata_type='videos')

                             # Entries  # Features  Avg. Entries per feature  \
Split Dataset
Train Main                      294805      131073                      5.15
      Query Videos Metadata     294805       82840                      0.92
      Label Videos Metadata     131073       82840                      0.49
Test  Main                      134835      131073                      2.17
      Query Videos Metadata     134835       82840                      0.17
      Label Videos Metadata     131073       82840                      0.49

                             Avg. Feature per entry  Max. Entries per feature  \
Split Dataset
Train Main                                     2.29                      1553
      Query Videos Metadata                    0.26                        31
      Label Videos Metadata                    0.31                        14
Test  Main                                     2.11                       705
      Query Videos Metadata                    0.10                        14
      Label Videos Metadata                    0.31                        14

                             Max. Feature per entry  # Features without entry  \
Split Dataset
Train Main                                        7                         0
      Query Videos Metadata                      10                     12830
      Label Videos Metadata                      10                     44398
Test  Main                                        6                         0
      Query Videos Metadata                      10                     69786
      Label Videos Metadata                      10                     44398

                             # Entries without feature
Split Dataset
Train Main                                           0
      Query Videos Metadata                     275983
      Label Videos Metadata                     120451
Test  Main                                           0
      Query Videos Metadata                     130099
      Label Videos Metadata                     120451

data_input_text : Pegs in the Park
lbl2data_input_text : ['Sequence for Kids']
vid2data_input_text : []
vid2lbl2data_input_text : [['https://www.amazon.com/vdp/08f82b156c7449e9ab6262598ea69997?ref=dp_vse_rvc_0']]

data_input_text : Say Again, Please: Guide to Radio Communications (ASA Training Manuals)
lbl2data_input_text : ["Pilot's Pocket Handbook: Flight Calculations, Weather Decoder, Aviation Acronyms, Charts and Checklists, Pilot Memory Aids", 'Aviation Weather (FAA Handbooks)']
vid2data_input_text : []
vid2lbl2data_input_text : [[], []]

data_input_text : Confessions of a Serial Egg Donor
lbl2data_input_text : ['Third Wave Agenda: Being Feminist, Doing Feminism', 'The Baby Business: How Money, Science, and Politics Drive the Commerce of Conception']
vid2data_input_text : []
vid2lbl2data_input_text : [[], []]

data_input_text : My Utmost For His Highest
lbl2data_input_text : ['Complete Works of Oswald Chambers: (Includes CD-Rom) (OSWALD CHAMBERS LIBRARY)']
vid2data_input_text : []
vid2lbl2data_input_text : [[]]

data_input_text : Softspots Women's Tela Leather Sandal
lbl2data_input_text : ["Softspots Women's Trinidad Slip-On", "Trotters Women's Liz Loafer"]
vid2data_input_text : []
vid2lbl2data_input_text : [[], []]

data_input_text : Holy Cows And Hog Heaven: The Food Buyer's Guide To Farm Friendly Food
lbl2data_input_text : ['Pastured Poultry Profits', 'Salad Bar Beef', "You Can Farm: The Entrepreneur's Guide to Start & Succeed in a Farming Enterprise"]
vid2data_input_text : []
vid2lbl2data_input_text : [['https://www.amazon.com/vdp/0296865b4ebe46929518079c8bdf31d2?ref=dp_vse_rvc_0', 'https://www.amazon.com/vdp/0fedc50a7015400aa6b5d07c185e5afa?ref=dp_vse_rvc_1'], [], []]

data_input_text : Amazon.com: Poodle Skirt - Adult Medium / Large Sz - Purple: Clothing
lbl2data_input_text : ['Amazon.com: Black Elastic Cinch Belt - Medium: Clothing', 'Amazon.com: Adult Sz 9-11 Bobby Socks w Black Poodle: Clothing']
vid2data_input_text : []
vid2lbl2data_input_text : [[], []]

data_input_text : The Rudolph Valentino Collection : THE MARRIED VIRGIN (1918), THE SHEIK (1921), BLOOD AND SAND (1922), COBRA (1925), and THE EAGLE (1925) (2009)
lbl2data_input_text : ['The Sheik / The Son of the Sheik (Special Edition) (1921)', 'Intimate Biography: Rudolph Valentino - The Great Lover + The Four Horsemen of the Apocalypse (2006)', 'Beyond the Rocks (1922)', 'The Valentino Collection (The Young Rajah / Stolen Moments / A Society Sensation / Moran of the Lady Letty) (1920)']
vid2data_input_text : []
vid2lbl2data_input_text : [[], [], [], ['https://www.amazon.com/vdp/7614274ebd634f3dae9fedbf3a3e0729?ref=dp_vse_rvc_0', 'https://www.amazon.com/vdp/3bd1c579ceb64a8bbeed580c4c38fc2b?ref=dp_vse_rvc_1', 'https://www.amazon.com/vdp/133b4598495d44e7a680ba1b0af6577e?ref=dp_vse_rvc_2', 'https://www.amazon.com/vdp/3bf97015f5b54a81bd172bc9f26fe14a?ref=dp_vse_rvc_3', 'https://www.amazon.com/vdp/db705143afe544a788aa4a6217060faf?ref=dp_vse_rvc_4']]

data_input_text : Amazon.com: Fantasie Smoothing Full Cup Underwire Bra: Clothing
lbl2data_input_text : ['Amazon.com: Fantasie Smoothing Balcony Underwire Bra: Clothing', 'Amazon.com: Fantasie Smoothing Balcony T-Shirt Bra: Clothing']
vid2data_input_text : []
vid2lbl2data_input_text : [[], []]

data_input_text : Rachael Ray Furi FUR863 Furi Gusto-Grip Antimicrobial 2-piece set w/Bamboo case
lbl2data_input_text : ['Furi FUR626 Ozitech Diamond Fingers Pro Knife Sharpener', 'Furi Rachael Ray Ozitech Diamond Fingers Pro Knife Sharpener']
vid2data_input_text : []
vid2lbl2data_input_text : [['https://www.amazon.com/vdp/03971ae7fc8842528e014c7253814a0b?ref=dp_vse_rvc_0', 'https://www.amazon.com/vdp/d6dd92ca40b5434d8685b6b9f9ec8596?ref=dp_vse_rvc_1', 'https://www.amazon.com/vdp/99a2ca5757cb4f61a90e1771ba1413e8?ref=dp_vse_rvc_2', 'https://www.amazon.com/vdp/fb186671b7e04fccb89ffa22845f1fd4?ref=dp_vse_rvc_3', 'https://www.amazon.com/vdp/05d3d9ea292e43ea9cdbfbd7d4fd7dfd?ref=dp_vse_rvc_4', 'https://www.amazon.com/vdp/05f61f380dbc4c7e84f08de1f71979b7?ref=dp_vse_rvc_5', 'https://www.amazon.com/vdp/0cbde55a5ff94b04899a955152c1fc95?ref=dp_vse_rvc_6', 'https://www.amazon.com/vdp/0a606181737b428981c81362f9735a31?ref=dp_vse_rvc_7', 'https://www.amazon.com/vdp/0a942cf4cf224bddbfe345cbd71cfe17?ref=dp_vse_rvc_8', 'https://www.amazon.com/vdp/0459422771474aed97526ea90a1aaf08?ref=dp_vse_rvc_9'], ['https://www.amazon.com/vdp/03971ae7fc8842528e014c7253814a0b?ref=dp_vse_rvc_0', 'https://www.amazon.com/vdp/d6dd92ca40b5434d8685b6b9f9ec8596?ref=dp_vse_rvc_1', 'https://www.amazon.com/vdp/fb186671b7e04fccb89ffa22845f1fd4?ref=dp_vse_rvc_2', 'https://www.amazon.com/vdp/99a2ca5757cb4f61a90e1771ba1413e8?ref=dp_vse_rvc_3', 'https://www.amazon.com/vdp/08d2464b6cfd467b8d2857fab3c24815?ref=dp_vse_rvc_4', 'https://www.amazon.com/vdp/09be0697ead44dd8bc6e98b7a90c9608?ref=dp_vse_rvc_5', 'https://www.amazon.com/vdp/08e7695083cb4ca49ddb376b327ceb9f?ref=dp_vse_rvc_6', 'https://www.amazon.com/vdp/f27a05eb9c3d4ddc90dd4e9520d26254?ref=dp_vse_rvc_7', 'https://www.amazon.com/vdp/0a57c10d4c61463dbb21d2d2d615d982?ref=dp_vse_rvc_8', 'https://www.amazon.com/vdp/064772b87a8b4ae19dedf47143d7b248?ref=dp_vse_rvc_9']]

## `Images`

In [ ]:
show_func(metadata_type='images')

                             # Entries  # Features  Avg. Entries per feature  \
Split Dataset
Train Main                      294805      131073                      5.15
      Query Images Metadata     294805      361399                      0.86
      Label Images Metadata     131073      361399                      0.47
Test  Main                      134835      131073                      2.17
      Query Images Metadata     134835      361399                      0.14
      Label Images Metadata     131073      361399                      0.47

                             Avg. Feature per entry  Max. Entries per feature  \
Split Dataset
Train Main                                     2.29                      1553
      Query Images Metadata                    1.06                      2167
      Label Images Metadata                    1.29                      1249
Test  Main                                     2.11                       705
      Query Images Metadata                    0.38                       905
      Label Images Metadata                    1.29                      1249

                             Max. Feature per entry  # Features without entry  \
Split Dataset
Train Main                                        7                         0
      Query Images Metadata                      41                     66325
      Label Images Metadata                      41                    198489
Test  Main                                        6                         0
      Query Images Metadata                      22                    315741
      Label Images Metadata                      41                    198489

                             # Entries without feature
Split Dataset
Train Main                                           0
      Query Images Metadata                     110463
      Label Images Metadata                      29146
Test  Main                                           0
      Query Images Metadata                     105785
      Label Images Metadata                      29146

data_input_text : Pegs in the Park
lbl2data_input_text : ['Sequence for Kids']
img2data_input_text : ['https://m.media-amazon.com/images/I/5146HUGf2yL._AC_.jpg', 'https://m.media-amazon.com/images/I/51dGC7WtetL._AC_.jpg', 'https://m.media-amazon.com/images/I/61Zv3nxyLnL._AC_.jpg']
img2lbl2data_input_text : [['https://m.media-amazon.com/images/I/61RBvi+yYrL._AC_.jpg', 'https://m.media-amazon.com/images/I/51zB-vOOAFL._AC_.jpg', 'https://m.media-amazon.com/images/I/516HshqtysL._AC_.jpg', 'https://m.media-amazon.com/images/I/51ltmMeTwlL._AC_.jpg']]

data_input_text : Say Again, Please: Guide to Radio Communications (ASA Training Manuals)
lbl2data_input_text : ["Pilot's Pocket Handbook: Flight Calculations, Weather Decoder, Aviation Acronyms, Charts and Checklists, Pilot Memory Aids", 'Aviation Weather (FAA Handbooks)']
img2data_input_text : ['https://m.media-amazon.com/images/I/51jy6Z46AmL._SX404_BO1,204,203,200_.jpg']
img2lbl2data_input_text : [['https://m.media-amazon.com/images/I/51c-pQA2w5L._SY291_BO1,204,203,200_QL40_FMwebp_.jpg'], ['https://m.media-amazon.com/images/I/51AXaVyBB4L._SX374_BO1,204,203,200_.jpg']]

data_input_text : Confessions of a Serial Egg Donor
lbl2data_input_text : ['Third Wave Agenda: Being Feminist, Doing Feminism', 'The Baby Business: How Money, Science, and Politics Drive the Commerce of Conception']
img2data_input_text : ['https://m.media-amazon.com/images/I/41H0KQ27DEL._SY291_BO1,204,203,200_QL40_FMwebp_.jpg']
img2lbl2data_input_text : [['https://m.media-amazon.com/images/I/51YF637RF8L._SX309_BO1,204,203,200_.jpg'], ['https://m.media-amazon.com/images/I/51UtbK4gdRL._SX598_BO1,204,203,200_.jpg']]

data_input_text : My Utmost For His Highest
lbl2data_input_text : ['Complete Works of Oswald Chambers: (Includes CD-Rom) (OSWALD CHAMBERS LIBRARY)']
img2data_input_text : []
img2lbl2data_input_text : [['https://m.media-amazon.com/images/I/519aYm5928L._SY291_BO1,204,203,200_QL40_FMwebp_.jpg']]

data_input_text : Softspots Women's Tela Leather Sandal
lbl2data_input_text : ["Softspots Women's Trinidad Slip-On", "Trotters Women's Liz Loafer"]
img2data_input_text : []
img2lbl2data_input_text : [[], ['https://m.media-amazon.com/images/I/41fYIg7HXtL._AC_.jpg', 'https://m.media-amazon.com/images/I/51vqHNZDNFL._AC_.jpg', 'https://m.media-amazon.com/images/I/51yxI96C96L._AC_.jpg', 'https://m.media-amazon.com/images/I/31G8EAAyYxL._AC_.jpg', 'https://m.media-amazon.com/images/I/41r7WvzhYIL._AC_.jpg', 'https://m.media-amazon.com/images/I/41ER-O0i1QL._AC_.jpg', 'https://m.media-amazon.com/images/I/41PHLcl8wfL._AC_.jpg', 'https://m.media-amazon.com/images/I/41Xo1OdK7CL._AC_.jpg']]

data_input_text : Holy Cows And Hog Heaven: The Food Buyer's Guide To Farm Friendly Food
lbl2data_input_text : ['Pastured Poultry Profits', 'Salad Bar Beef', "You Can Farm: The Entrepreneur's Guide to Start & Succeed in a Farming Enterprise"]
img2data_input_text : ['https://m.media-amazon.com/images/I/51rd1E6FOTL._SY291_BO1,204,203,200_QL40_FMwebp_.jpg']
img2lbl2data_input_text : [['https://m.media-amazon.com/images/I/51CE1Y5-drL._SX338_BO1,204,203,200_.jpg'], ['https://m.media-amazon.com/images/I/51ueBfYXMeL._SX325_BO1,204,203,200_.jpg'], ['https://m.media-amazon.com/images/I/41yEwSh0Q4L._SY291_BO1,204,203,200_QL40_FMwebp_.jpg']]

data_input_text : Amazon.com: Poodle Skirt - Adult Medium / Large Sz - Purple: Clothing
lbl2data_input_text : ['Amazon.com: Black Elastic Cinch Belt - Medium: Clothing', 'Amazon.com: Adult Sz 9-11 Bobby Socks w Black Poodle: Clothing']
img2data_input_text : []
img2lbl2data_input_text : [[], []]

data_input_text : The Rudolph Valentino Collection : THE MARRIED VIRGIN (1918), THE SHEIK (1921), BLOOD AND SAND (1922), COBRA (1925), and THE EAGLE (1925) (2009)
lbl2data_input_text : ['The Sheik / The Son of the Sheik (Special Edition) (1921)', 'Intimate Biography: Rudolph Valentino - The Great Lover + The Four Horsemen of the Apocalypse (2006)', 'Beyond the Rocks (1922)', 'The Valentino Collection (The Young Rajah / Stolen Moments / A Society Sensation / Moran of the Lady Letty) (1920)']
img2data_input_text : ['https://m.media-amazon.com/images/I/51GGxUybeTL.jpg']
img2lbl2data_input_text : [['https://m.media-amazon.com/images/I/51P9S1PHJWL.jpg'], ['https://m.media-amazon.com/images/I/51Bgu+X4rNL.jpg'], ['https://m.media-amazon.com/images/I/51D+wuBZZgL.jpg'], ['https://m.media-amazon.com/images/I/41HTDUt4TIL.jpg']]

data_input_text : Amazon.com: Fantasie Smoothing Full Cup Underwire Bra: Clothing
lbl2data_input_text : ['Amazon.com: Fantasie Smoothing Balcony Underwire Bra: Clothing', 'Amazon.com: Fantasie Smoothing Balcony T-Shirt Bra: Clothing']
img2data_input_text : []
img2lbl2data_input_text : [['https://m.media-amazon.com/images/I/51E9n5YMDZL._AC_.jpg', 'https://m.media-amazon.com/images/I/218RY9YFVNL._AC_.jpg', 'https://m.media-amazon.com/images/I/212BVD8B0HL._AC_.jpg', 'https://m.media-amazon.com/images/I/317BVVE3T5L._AC_.jpg'], ['https://m.media-amazon.com/images/I/41Sdlde2R5L._AC_.jpg']]

data_input_text : Rachael Ray Furi FUR863 Furi Gusto-Grip Antimicrobial 2-piece set w/Bamboo case
lbl2data_input_text : ['Furi FUR626 Ozitech Diamond Fingers Pro Knife Sharpener', 'Furi Rachael Ray Ozitech Diamond Fingers Pro Knife Sharpener']
img2data_input_text : []
img2lbl2data_input_text : [['https://m.media-amazon.com/images/I/41t--GHJvpL._AC_.jpg', 'https://m.media-amazon.com/images/I/51m5sZs3jfL._AC_.jpg', 'https://m.media-amazon.com/images/I/51NSf8NVH2L._AC_.jpg', 'https://m.media-amazon.com/images/I/51WtUqFWZTL._AC_.jpg', 'https://m.media-amazon.com/images/I/412vLy4eTML._AC_.jpg', 'https://m.media-amazon.com/images/I/51r67G5HO3L._AC_.jpg', 'https://m.media-amazon.com/images/I/51J+CITeHEL._AC_.jpg', 'https://m.media-amazon.com/images/I/51d9AITGnEL._AC_.jpg', 'https://m.media-amazon.com/images/I/512oHp8eSFL._AC_.jpg'], ['https://m.media-amazon.com/images/I/41t--GHJvpL._AC_.jpg', 'https://m.media-amazon.com/images/I/51m5sZs3jfL._AC_.jpg', 'https://m.media-amazon.com/images/I/51NSf8NVH2L._AC_.jpg', 'https://m.media-amazon.com/images/I/51WtUqFWZTL._AC_.jpg', 'https://m.media-amazon.com/images/I/412vLy4eTML._AC_.jpg', 'https://m.media-amazon.com/images/I/51r67G5HO3L._AC_.jpg', 'https://m.media-amazon.com/images/I/51J+CITeHEL._AC_.jpg', 'https://m.media-amazon.com/images/I/51d9AITGnEL._AC_.jpg', 'https://m.media-amazon.com/images/I/512oHp8eSFL._AC_.jpg']]