In [ ]:
%reload_ext autoreload
%autoreload 2

In [ ]:
import numpy as np
from functools import partial

import xclib.data.data_utils as du, scipy.sparse as sp

from sugar.statistics import *
from sugar.core import *
from xcai.data import *

## `MSMARCO`

In [ ]:
data_dir = '/home/scai/phd/aiz218323/scratch/datasets/msmarco/XC'

indices = np.random.permutation(6980)[:10]
show_func = partial(show_dataset, data_dir, idxs=indices)

### `entity-gpt`

In [ ]:
o = show_func(metadata_type='entity', suffix='gpt', use_trn=False)

                             # Entries  # Features  Avg. Entries per feature  \
Split Dataset
Train Main                      502939     8841823                  6.03e-02
      Query Entity Metadata     502939      207109                  3.81e+00
      Label Entity Metadata    8841823      207109                  0.00e+00
Test  Main                        6980     8841823                  8.41e-04
      Query Entity Metadata       6980      207109                  2.57e-02
      Label Entity Metadata    8841823      207109                  0.00e+00

                             Avg. Feature per entry  Max. Entries per feature  \
Split Dataset
Train Main                                     1.06                        17
      Query Entity Metadata                    1.57                      6469
      Label Entity Metadata                    0.00                         0
Test  Main                                     1.07                         2
      Query Entity Metadata                    0.76                        71
      Label Entity Metadata                    0.00                         0

                             Max. Feature per entry  # Features without entry  \
Split Dataset
Train Main                                        7                   8325351
      Query Entity Metadata                      27                         0
      Label Entity Metadata                       0                    207109
Test  Main                                        4                   8834390
      Query Entity Metadata                      11                    203538
      Label Entity Metadata                       0                    207109

                             # Entries without feature
Split Dataset
Train Main                                           0
      Query Entity Metadata                      28386
      Label Entity Metadata                    8841823
Test  Main                                           0
      Query Entity Metadata                       3821
      Label Entity Metadata                    8841823

data_input_text : what county is champlain va located in
lbl2data_input_text : ["Champlain, Virginia. Champlain is an unincorporated community in Essex County, Virginia, United States. It lies at the junction of U.S. Route 17 and Route 631. It is located mainly in a rural community. Champlain's zip code is 22438. The Glebe House of St. Anne's Parish, St. Matthew's Church, and Linden are listed on the National Register of Historic Places. References"]
ent2data_input_text : ['champlain', 'virginia', 'county']
ent2lbl2data_input_text : [[]]

data_input_text : what causes constant bloating and gas
lbl2data_input_text : ["Excess gas may be a symptom of a more serious chronic condition. Examples include diverticulitis or an inflammatory bowel disease, such as ulcerative colitis or Crohn's disease. Excess gas and bloating may also be a symptom of bacterial overgrowth in the small intestine from conditions such as diabetes."]
ent2data_input_text : []
ent2lbl2data_input_text : [[]]

data_input_text : what is mhs?
lbl2data_input_text : ['A leading publisher of scientifically validated assessments for more than 30 years, Multi-Health Systems Inc. (MHS) serves clients in educational, clinical, corporate, public safety, government, military, pharmaceutical, and research settings.']
ent2data_input_text : []
ent2lbl2data_input_text : [[]]

data_input_text : convulsion definition
lbl2data_input_text : ['Full Definition of CONVULSION. 1. : an abnormal violent and involuntary contraction or series of contractions of the muscles. 2. a: a violent disturbance b: an uncontrolled fit: paroxysm. Ã¢Â\x80Â\x94 conÃ\x82Â·vulÃ\x82Â·sionÃ\x82Â·ary \\-shÃ\x89Â\x99-Ã\x8bÂ\x8cner-Ã\x84Â\x93\\ adjective.See convulsion defined for English-language learners. See convulsion defined for kids.edical: a sudden violent shaking of the muscles in your body that you are unable to control. : a sudden experience of something (such as laughter) that shakes or moves your body.']
ent2data_input_text : []
ent2lbl2data_input_text : [[]]

data_input_text : who was susan calvin in i robot
lbl2data_input_text : ['In I, Robot, by Isaac Asimov, Dr. Susan Calvin, the main character, reveals much about herself to the reader, and makes the book what it is. Many times during the novel, Dr. Calvin displays amazing intelligence in tough situations. When analyzing the mind reading robot named Herbie, Dr. Susan Calvin displays great amounts of intelligence.']
ent2data_input_text : []
ent2lbl2data_input_text : [[]]

data_input_text : what is csfb
lbl2data_input_text : ['Circuit Switched FallBack. (CSFB) Circuit Switched FallBack (CSFB) is a technology whereby voice and SMS services are delivered to LTE devices through the use of GSM or another circuit-switched network. Circuit Switched FallBack is needed because LTE is a packet-based all-IP network that cannot support circuit-switched calls.']
ent2data_input_text : []
ent2lbl2data_input_text : [[]]

data_input_text : siamese cats types of breeds
lbl2data_input_text : ['The Siamese is a medium-sized, light-colored cat with stunning sapphire eyes. It is one of the most ancient breeds. There are two types of Siamese: traditional and show. The Show Siamese is very angular, elegant and slender breed. The Traditional Siamese is more round and chunky. Personality: Siamese cats are very active, talkative and curious cats.']
ent2data_input_text : []
ent2lbl2data_input_text : [[]]

data_input_text : how many units for frown lines
lbl2data_input_text : ['Depending on the size and strength of these muscles our physicians will determine how many units are needed. The average amount of Botox used for the Frown lines is around 20-24 Botox units for a female and about 20 to 30 units for male patients as their facial muscles are often larger, thicker and stronger.']
ent2data_input_text : ['frown lines', 'units']
ent2lbl2data_input_text : [[]]

data_input_text : where is kashi china
lbl2data_input_text : ['Kashi (Kashgar) is located in southwestern Xinjiang Uygur Autonomous Region - a far west province in China. I visited the city several years ago. It was 6 p.m. when I stood in the square in front of the Aitika Mosque in the city, in southwestern Xinjiang. I met a group of farmers of the Uygur ethnic group.']
ent2data_input_text : []
ent2lbl2data_input_text : [[]]

data_input_text : who is robert walton
lbl2data_input_text : ['The novel itself begins with a series of letters from the explorer Robert Walton to his sister, Margaret Saville. Walton, a well-to-do Englishman with a passion for seafaring, is the captain of a ship headed on a dangerous voyage to the North Pole.']
ent2data_input_text : []
ent2lbl2data_input_text : [[]]

### `entity-llama`

In [ ]:
o = show_func(metadata_type='entity', suffix='llama', use_trn=False)

                             # Entries  # Features  Avg. Entries per feature  \
Split Dataset
Train Main                      502939     8841823                  6.03e-02
      Query Entity Metadata     502939      200337                  3.74e+00
      Label Entity Metadata    8841823      200337                  0.00e+00
Test  Main                        6980     8841823                  8.41e-04
      Query Entity Metadata       6980      200337                  3.90e-02
      Label Entity Metadata    8841823      200337                  0.00e+00

                             Avg. Feature per entry  Max. Entries per feature  \
Split Dataset
Train Main                                     1.06                        17
      Query Entity Metadata                    1.49                      6906
      Label Entity Metadata                    0.00                         0
Test  Main                                     1.07                         2
      Query Entity Metadata                    1.12                        68
      Label Entity Metadata                    0.00                         0

                             Max. Feature per entry  # Features without entry  \
Split Dataset
Train Main                                        7                   8325351
      Query Entity Metadata                      24                         0
      Label Entity Metadata                       0                    200337
Test  Main                                        4                   8834390
      Query Entity Metadata                      16                    195395
      Label Entity Metadata                       0                    200337

                             # Entries without feature
Split Dataset
Train Main                                           0
      Query Entity Metadata                      30245
      Label Entity Metadata                    8841823
Test  Main                                           0
      Query Entity Metadata                       2047
      Label Entity Metadata                    8841823

data_input_text : what county is champlain va located in
lbl2data_input_text : ["Champlain, Virginia. Champlain is an unincorporated community in Essex County, Virginia, United States. It lies at the junction of U.S. Route 17 and Route 631. It is located mainly in a rural community. Champlain's zip code is 22438. The Glebe House of St. Anne's Parish, St. Matthew's Church, and Linden are listed on the National Register of Historic Places. References"]
ent2data_input_text : ['champlain', 'va']
ent2lbl2data_input_text : [[]]

data_input_text : what causes constant bloating and gas
lbl2data_input_text : ["Excess gas may be a symptom of a more serious chronic condition. Examples include diverticulitis or an inflammatory bowel disease, such as ulcerative colitis or Crohn's disease. Excess gas and bloating may also be a symptom of bacterial overgrowth in the small intestine from conditions such as diabetes."]
ent2data_input_text : ['bloating', 'gas']
ent2lbl2data_input_text : [[]]

data_input_text : what is mhs?
lbl2data_input_text : ['A leading publisher of scientifically validated assessments for more than 30 years, Multi-Health Systems Inc. (MHS) serves clients in educational, clinical, corporate, public safety, government, military, pharmaceutical, and research settings.']
ent2data_input_text : ['mhs']
ent2lbl2data_input_text : [[]]

data_input_text : convulsion definition
lbl2data_input_text : ['Full Definition of CONVULSION. 1. : an abnormal violent and involuntary contraction or series of contractions of the muscles. 2. a: a violent disturbance b: an uncontrolled fit: paroxysm. Ã¢Â\x80Â\x94 conÃ\x82Â·vulÃ\x82Â·sionÃ\x82Â·ary \\-shÃ\x89Â\x99-Ã\x8bÂ\x8cner-Ã\x84Â\x93\\ adjective.See convulsion defined for English-language learners. See convulsion defined for kids.edical: a sudden violent shaking of the muscles in your body that you are unable to control. : a sudden experience of something (such as laughter) that shakes or moves your body.']
ent2data_input_text : []
ent2lbl2data_input_text : [[]]

data_input_text : who was susan calvin in i robot
lbl2data_input_text : ['In I, Robot, by Isaac Asimov, Dr. Susan Calvin, the main character, reveals much about herself to the reader, and makes the book what it is. Many times during the novel, Dr. Calvin displays amazing intelligence in tough situations. When analyzing the mind reading robot named Herbie, Dr. Susan Calvin displays great amounts of intelligence.']
ent2data_input_text : []
ent2lbl2data_input_text : [[]]

data_input_text : what is csfb
lbl2data_input_text : ['Circuit Switched FallBack. (CSFB) Circuit Switched FallBack (CSFB) is a technology whereby voice and SMS services are delivered to LTE devices through the use of GSM or another circuit-switched network. Circuit Switched FallBack is needed because LTE is a packet-based all-IP network that cannot support circuit-switched calls.']
ent2data_input_text : []
ent2lbl2data_input_text : [[]]

data_input_text : siamese cats types of breeds
lbl2data_input_text : ['The Siamese is a medium-sized, light-colored cat with stunning sapphire eyes. It is one of the most ancient breeds. There are two types of Siamese: traditional and show. The Show Siamese is very angular, elegant and slender breed. The Traditional Siamese is more round and chunky. Personality: Siamese cats are very active, talkative and curious cats.']
ent2data_input_text : ['siamese']
ent2lbl2data_input_text : [[]]

data_input_text : how many units for frown lines
lbl2data_input_text : ['Depending on the size and strength of these muscles our physicians will determine how many units are needed. The average amount of Botox used for the Frown lines is around 20-24 Botox units for a female and about 20 to 30 units for male patients as their facial muscles are often larger, thicker and stronger.']
ent2data_input_text : ['frown lines', 'units']
ent2lbl2data_input_text : [[]]

data_input_text : where is kashi china
lbl2data_input_text : ['Kashi (Kashgar) is located in southwestern Xinjiang Uygur Autonomous Region - a far west province in China. I visited the city several years ago. It was 6 p.m. when I stood in the square in front of the Aitika Mosque in the city, in southwestern Xinjiang. I met a group of farmers of the Uygur ethnic group.']
ent2data_input_text : ['china']
ent2lbl2data_input_text : [[]]

data_input_text : who is robert walton
lbl2data_input_text : ['The novel itself begins with a series of letters from the explorer Robert Walton to his sister, Margaret Saville. Walton, a well-to-do Englishman with a passion for seafaring, is the captain of a ship headed on a dangerous voyage to the North Pole.']
ent2data_input_text : []
ent2lbl2data_input_text : [[]]